### ISSUE TITLE
When editing tags, the activities included display incorrectly

### ISSUE THREAD

**Issue by ficion** [Razeeman/Android-SimpleTimeTracker#1]
In the screen to add or edit tags, the activities no included (all by default) appear as if they were (in color), while the ones that one selects for inclusion appear as disabled (in gray).

**Comment by Razeeman** [comment]
Thank you for the feedback.

This is intended behaviour. Greyed out activities means that they are selected. Same as how on the main screen activities selected for tracking are greyed out. Although I understand how it can be confusing, but reversing this logic also can be confusing for some users. I think a better idea would be to change ui and split activity list into available for selection and already selected. When user select activity for inclusion it would appear in the "selected" list.

How do you think, is it a good idea? Anyway, thanks again!

**Comment by ficion** [comment]
I find it surprising it is the intended behavior, since I haven't seen an interface where gray means selected. Either way, the idea you mention seems better!

**Comment by Razeeman** [comment]
Changed in 1.9
