### ISSUE TITLE
[Suggestion] Wifi/Location based triggers

### ISSUE THREAD

**Issue by Luk164** [Razeeman/Android-SimpleTimeTracker#10]
Basically, I would like my phone to check if I am on company wifi/on premises and start logging that time. Same could go for stuff like gym, being home and other activities.

**Comment by sanderpoks** [comment]
This could be done with Tasker if there was some kind of API or intents for starting/stopping tracking.

**Comment by Razeeman** [comment]
Added integration with Tasker to allow this king of tracking. Thank you for the suggestion.
