### ISSUE TITLE
Bug: Some untracked time is not shown in the second tab

### ISSUE THREAD

**Issue by froyglez** [Razeeman/Android-SimpleTimeTracker#104]
Sometimes the untracked time between an activity and other is not shown, for example (see the image):![Screenshot_2023-05-12-08-50-43-077_com.razeeman.util.simpletimetracker.jpg](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/60108777/76724e49-7d80-477e-a595-b60614e7e017)

**Comment by Razeeman** [comment]
Hello! Untracked time shorter than 1 minute is filtered out to avoid clutter in records list.

**Comment by Razeeman** [comment]
Added a setting to change this constant. Will be in the next release.
