### ISSUE TITLE
[Feature request] Split statistics by tag

### ISSUE THREAD

**Issue by Lusito** [Razeeman/Android-SimpleTimeTracker#105]
Just stumbled upon this and I like it very much. One thing requires me to make a lot of very similar activities though:

On the statistics page, all times for one day are merged together. I would like to suggest an optional split by tag.

Example use case:
- I have different activities: concept, design, development, communication, documentation
- I have different tags: project A/B/C/D

Let's say, I have these entries:
- concept [project a] 1h
- concept [project b] 2h
- development [project a] 2h
- concept [project b] 1h
- development [project a] 2h

For this I would like to see:
- concept [project a] 1h
- concept [project b] 3h
- development [project a] 4h

I'd have to create 5x4 = 20 activities to make the above scenario work (one for each activity + tag combination).
Sadly, my real world scenario is more like 6 activities and 15 tags. I'm not gonna create 90 activities, so for now I'll try it and check how much work it is to manually sum them up.

Thanks for the great work!

**Comment by Razeeman** [comment]
Hello! This information can be viewed from detailed statistics, which is available by clicking on some card on the statistics tab. There will be a tag distribution at the bottom. Is this what you are looking for?

**Comment by Lusito** [comment]
Hello, yes. I completely missed that you can click on the activity on that screen.

Thank you!
