### ISSUE TITLE
Feature request: setting to remove semi-transparent background of widget

### ISSUE THREAD

**Issue by MrPixelized** [Razeeman/Android-SimpleTimeTracker#106]
Especially for the statistics chart, having a nice desktop wallpaper without the semi transparent background could look nicer.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. It could be possible but seems like it would also require ability to change text / icon color on widget otherwise they will not be visible on light background.

**Comment by MrPixelized** [comment]
By the way, unrelated to this feature request: thank you for creating this application. It's helped me get insights into myself that would otherwise have taken me much longer to get. The app is great, works well, looks stellar, functions without hiccups. Your work is much appreciated! Do you take donations?

**Comment by MrPixelized** [comment]
You could have a selection of four widgets:

- light theme semi-transparent
- dark theme semi-transparent
- light theme transparent
- dark theme transparent

All essentially the same but with different styling. No need to make the background and text separately adjustable, just these four options in the widget selection menu. Would be easier to use as well.

Another option is to use light text with a black border for the transparent-background widget.

**Comment by Razeeman** [comment]
Hello again! A setting to change widget background transparency was added in the latest release. Thank you again for the suggestion.
