### ISSUE TITLE
detailed statistics always selects today instead of the source date

### ISSUE THREAD

**Issue by Lusito** [Razeeman/Android-SimpleTimeTracker#108]
When I click on an activity on the statistics page for a past date, it will show the details for today instead and I have to use the date picker to correct this.

Version 1.26

**Comment by Razeeman** [comment]
Hello! Can you check if "keep statistics range" setting is enabled? Selected date on statistics is passed to detailed statistics only if it is enabled.

**Comment by Lusito** [comment]
Thanks, that was not checked and it fixes the issue. I wonder why it is not selected by default. What use-case is the unchecked setting for?
I can't imagine anyone wanting to go to today when clicking on an activity like that

**Comment by Razeeman** [comment]
Range in the context of this setting is more about a day, week, month etc range. The use-case for example is to view statistics page on one range and detailed statistics on a different range. For example I keep my statistics page on a day range to have overview of today, but when activity clicked detailed statistics opens on a week range, to have a week overview. Hope this makes sense.
