### ISSUE TITLE
Statistcs only show the entries created since last update

### ISSUE THREAD

**Issue by UristMcEngineer** [Razeeman/Android-SimpleTimeTracker#110]
Since updating to Version 1.27 through F-Droid the statistics only show information about the entries created since then even though the earlier entries are still there.
I am using a Pixel 3a with Android Version 12.

**Comment by Razeeman** [comment]
Hello! Can you please send some screenshots of the second tab (records) on an earlier date, and of the third tab (statistics) on the same date? If I understood correctly, the second tab would show some records that are not shown on third tab?

**Comment by UristMcEngineer** [comment]
It shows even in the third tab, but not in the details and list of entries that you can open from the third tab.

![Screenshot_20230625-130555](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/19378064/90c43e27-1c27-490b-983d-05e69d276fb8)
![Screenshot_20230625-130613](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/19378064/70566c21-b69f-4d6e-bf4b-7c3b98184aee)
![Screenshot_20230625-130648](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/19378064/e1c7f598-ad27-472c-987d-0544b8580337)

**Comment by UristMcEngineer** [comment]
This is an example of a category in which i did not create any entries since the update. For other categories it only shows those entries created since the update

**Comment by Razeeman** [comment]
Thank you for the information. On the screenshots it seems that the statistics (third tab) is for the yesterday (gestern) and detailed statistics (screen that opens by clicking on some activity on the third tab) is for today (heute). Can you check detailed statistics also for yesterday (by opening it and clicking the left arrow at the bottom). This way statistics and detailed statistics will show information for the same date.

**Comment by UristMcEngineer** [comment]
This is indeed the only problem. It seems that I was used to it showing all entries by default and now it only showed those from today by default and I did not realise it. Sorry for taking up your time.
Thanks for the quick response and your work on the app!
