### ISSUE TITLE
Feature Request: Follow System Theme

### ISSUE THREAD

**Issue by ghost** [Razeeman/Android-SimpleTimeTracker#112]
Hello! First wanted to say that your app was perfect for what I needed, and thanks for developing it!

One thing I noticed is that there's an option to select dark mode manually in the app, but would you be able to add a setting so it automatically matches the system dark/light theme?

Thanks!

**Comment by Razeeman** [comment]
Hello! Glad you liked the app and thank you for the suggestion. Implemented it in latest commits, will be in the next release.
