### ISSUE TITLE
Custom Order not persisted correctly

### ISSUE THREAD

**Issue by sbungartz** [Razeeman/Android-SimpleTimeTracker#12]
Hi, thanks for creating this neat and handy app!

I have a problem with the custom order of RecordTypes.

I had 33 RecordTypes, 3 of which were archived and I had set up a custom order for them. Today I created a 34th Record Type.

I had already noticed that new RecordTypes are just placed in (apparently) random spot within a custom ordered list – I would have expected them to be added to the end instead.
But that would not be much of an issue since I would probably want to change the position in the order anyway.

So that's what I did: I went into the settings, changed the Position of the new RecordType to where I wanted it to sit. It showed up fine in the Dialog, but after dismissing it, another RecordType was in its spot instead.
After a couple of retries the custom order now seems completely broken – I cannot spot the pattern in which the saved result differs from what I had intended.

I also noticed that the custom order is not included in the `.backup` file. That's something I would also appreciate (and might help debug/fix/workaround this issue).

If I find the time I will try to debug this further and get back here, but in the meantime, maybe you already have an Idea to what might cause this to suddenly and (apparently) permanently break.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. I think I found the bug that was causing this. It will probably be fixed in the next update.

As for the saving settings into the backup file - thank you for the suggestion, it is planned for the future updates, but can't tell for sure when exactly it will be implemented.

**Comment by sbungartz** [comment]
Cool, thank you very much for the quick response!

**Comment by Razeeman** [comment]
Hope it's fixed in 1.14

**Comment by sbungartz** [comment]
Seems to work great now, thanks!
