### ISSUE TITLE
Zombie entries 

### ISSUE THREAD

**Issue by Der-N** [Razeeman/Android-SimpleTimeTracker#120]
Version 1.29 creates "Zombie" entries:

Starting an activity on one day, forgetting to stop the activity the same day, and editing it the following day, to stop the day before, does the following:

1. Last days activity is logged as expected
2. An additional grey activity is created,  showing "? Untracked Time"

This didn't happen before Version 1.29.

Best regards

**Comment by alphanerdgen** [comment]
I'm also facing the same issue in version 1.29. Android 12.

![Uploading Screenshot_Simple Time Tracker.png…]()

**Comment by alphanerdgen** [comment]
@Der-N Found a solution:

Settings > Display Settings > Deselect 'Show untracked time in records' and 'Show untracked time in statistics'.

**Comment by Der-N** [comment]
> @Der-N Found a solution:
> 
> Settings > Display Settings > Deselect 'Show untracked time in records' and 'Show untracked time in statistics'.

@alphanerdgen: Great, thanks. That is working for me also
