### ISSUE TITLE
Found an translation mistake in the Simplified Chinese: "session" should not be translated as "会议".

### ISSUE THREAD

**Issue by Horiz21** [Razeeman/Android-SimpleTimeTracker#123]
"Session" has multiple meanings in Chinese, and "会议" means "meeting/conference." However, I believe that in the context of the goal, "session" should mean "one-time" or "period." Therefore, this is a clear translation mistake, which also caused me to be unable to understand why there is an option similar to "meeting" in the goal for a long time.

The correct translations for "session" could be:

1. "一次": one time
2. "单次": single time
3. "次": omitting the numeral, but still conveying the meaning of single time
4. "节," "段," or "阶段": These are references to the translation "節段" in Traditional Chinese, which is correct. Therefore, if you want to correspond to Traditional Chinese, you can use the translation "节," "段," or "阶段."

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. Changed it to "阶段". It will be in the next release.
