### ISSUE TITLE
[ Bug ] [ Feature Request ] Monthly statistic widget showing today metrics, Widget for Goals

### ISSUE THREAD

**Issue by gpsarathy** [Razeeman/Android-SimpleTimeTracker#124]
[ Bug ]  Monthly statistic widget showing today metrics
I have fixed widget for monthly statistics in homescreen, now I noticed its rolled back to today.
I tried to recreate with month but it set back to today
fyi - I'm using latest android playstore release. Not interacted with any settings recently or added any filters in widget customization.

 [ Feature Request ]  Widget for Goals
Similar to universal widget runner, highlighted the widget to show the activities that's goals are reached.
I'm not sure Implementation wise how you determine goal time reached, since we have multiple session goal. Hopefully if that can be user choice that'll be great

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. According the bug, can it be the case that on the 1st of september widgets for day statistics and month statistics was showing the same data because the month has only started?

**Comment by gpsarathy** [comment]
Yes. I've misinterpreted month to Last 30 days. Not a bug.
