### ISSUE TITLE
Goals on separate tab not displaying

### ISSUE THREAD

**Issue by Laytongentleman** [Razeeman/Android-SimpleTimeTracker#125]
I set up time goals, then I had them visible in the separate the tab.
But after one day, they no longer display even if I set up new goals.

**Comment by Razeeman** [comment]
Hello! There is a bug in the latest release, when statistics filter on the third tab is not set up to Activity - goals on the goal tab are not shown. It  will be fixed in the next release. Can you please check, may be this is the case?

**Comment by Razeeman** [comment]
Bug was fixed sometime ago, should be working now.

**Comment by Laytongentleman** [comment]
Thanks I had noticed it worked some time ago as you say !

Ps:
Best of luck for you project, your app is perfect, it carries my life and habits for more than a year now.
