### ISSUE TITLE
[Feature Request] Android custom icon theming support

### ISSUE THREAD

**Issue by ghost** [Razeeman/Android-SimpleTimeTracker#126]
Would it be possible to support custom icon theming? Would be cool to have simple time tracker match the other apps on the home screen :) Thanks again for all the work on the app!

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. A pull request #121 was merged recently, it will be in the next release. Is this what you are looking for?

**Comment by ghost** [comment]
Yeah that's exactly what I had meant! Thanks!

**Comment by Razeeman** [comment]
Mentioned PR was merged and released.
