### ISSUE TITLE
[Feature Request] option for extra tab for calendar view

### ISSUE THREAD

**Issue by unencryptid** [Razeeman/Android-SimpleTimeTracker#127]
I find myself wanting to switch between the normal records and calendar view quite often, and it's getting painful to go back to the settings each time. I saw there was already a closed issue on this topic [here](https://github.com/Razeeman/Android-SimpleTimeTracker/issues/46), but having the calendar view as an extra tab or a toggle would be very useful to me. It's already an option to add an extra tab for goals, so I think having a calendar tab option would make sense.

**Comment by ajtga** [comment]
Yes. For me it would be very useful as well. I prefer editing the records using the normal view and visualizing it using the calendar view. So an extra tab with a different view, or a simple button to switch between views would be great.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. Added an option to show toggle to switch between the list and calendar, toggle will be on the same tab. Will be in the next release.
