### ISSUE TITLE
App is sold in AppGallery

### ISSUE THREAD

**Issue by Lijucay** [Razeeman/Android-SimpleTimeTracker#130]
Hey dev,

While searching for things in AppGallery, I found out that there is a "dev" who sells applications that aren't his own.

I try to contact as many devs as possible to inform them about the thing. Here is a link:
https://appgallery.huawei.com/app/C108336043

I already contacted Huawei about that and I hope they'll help us asap.

**Comment by Razeeman** [comment]
Hello! Thank you for pointing it out. Looks like it was removed from there.
