### ISSUE TITLE
How are category icons picked in the Category statistics pie chart?

### ISSUE THREAD

**Issue by jake-goldsmith** [Razeeman/Android-SimpleTimeTracker#137]
In the statistics view when in the Categories mode it seems like each category picks the icon from one of activities in the category. I don't really like the selected icons so was wondering if there is a way I can force the system to pick a particular icon from one of the activities?

Any ideas? Or can you point me to the relevant part of the code?

Many thanks!

**Comment by Razeeman** [comment]
Hello! Icon is selected from the first activity that was added to category, so to force some icon, you can remove from category all activities except one with this particular icon, save category, and than add all activities back to category. Hope this helps.

**Comment by Razeeman** [comment]
Closed issue by mistake, sorry. If you have any more questions feel free to comment or reopen.

**Comment by jake-goldsmith** [comment]
Hi, that's all good, I just tested it and the fix worked to update the icon. Thanks for the help!
