### ISSUE TITLE
Archiving A then renaming B -> A breaks A

### ISSUE THREAD

**Issue by DuckDuckWhale** [Razeeman/Android-SimpleTimeTracker#142]
1. Make activity A
2. Make activity B
3. Archive A
4. Rename B to A
5. A is no longer archived somehow and now they have the same color and icon with one of them being overwritten

Version 1.31 from F-Droid

**Comment by Razeeman** [comment]
Related to #131 

Hello! Thank you for the feedback. Should be fixed in the latest release.
