### ISSUE TITLE
shown in possible? 

### ISSUE THREAD

**Issue by yourmother9** [Razeeman/Android-SimpleTimeTracker#146]
is it possible to show a running timer in the lock screen? 
because i always forget that a timer is running.

**Comment by cogk** [comment]
Hello, there is a checkbox called “Show timer notifications” in the “Notification settings” section.

![image](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/10946971/04a6da5d-0074-4c90-87b2-2981ebee1268)

Maybe this could be enough? This silent notification shows up on the lock screen.

**Comment by yourmother9** [comment]
yes i know, but this pictogram is like any other alarm clock has. 
so i need always guess what kind of alarm this is. 
its also not stand out enough.  to small. my bar is full of this pictograms. 

no i need a remember in the lock screen so its remember me there is a timer running.

**Comment by yourmother9** [comment]
another question:

How do i open spreadsheet?
only office can't open it. it says: "invalid file extension"

**Comment by Razeeman** [comment]
Hello! When "Show timer notifications" setting is enabled a constant notification should be shown in the notifications tray and on the lock screen. It should look like on the attached screenshot. If it is not shown can you please check system settings for the app, maybe notifications are disabled in the system. 

As for the spreadsheet, it can be opened with any program that supports csv files. 

![IMG_20240116_190657](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/5223302/c882b8c9-6b4d-4cdb-8d38-bad249a36ee5)

**Comment by yourmother9** [comment]
Thanks!!!
I got it working. 
there are so much options to play with pfff haha. 
i like this app more and more. 

ok another question. 
Can i set somehow that the app only record one timer?

when i export spreadsheet now, all timers are mixed up in spreadsheet. 
so for example: 
i use timers for: 
Cooking
Training
working
etc. 
If i export spreadsheet now, all these timers are mixed up in spreadsheet. 
One big mess.

I don't want the app record every timer i use into spreadsheet.
What i want is to record one timer and all other timers not. 
 
Is this possible?

**Comment by yourmother9** [comment]
> Hello! When "Show timer notifications" setting is enabled a constant notification should be shown in the notifications tray and on the lock screen. It should look like on the attached screenshot. If it is not shown can you please check system settings for the app, maybe notifications are disabled in the system.
> 
> As for the spreadsheet, it can be opened with any program that supports csv files.
> 
> ![IMG_20240116_190657](https://private-user-images.githubusercontent.com/5223302/297116635-c882b8c9-6b4d-4cdb-8d38-bad249a36ee5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDE4OTIsIm5iZiI6MTcwNjMwMTU5MiwicGF0aCI6Ii81MjIzMzAyLzI5NzExNjYzNS1jODgyYjhjOS02YjRkLTRjZGItOGQzOC1iYWQyNDlhMzZlZTUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMjAzOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDUzOTNhMjRjZTVkODIxM2UyZjNmNDg1MDUwZWQ2N2UyZDlhZDNiMGI0Mjg1ZDA3ODVhZDQzNTY2ZGFmMTczMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WUFlGryFC4ZWYq8dEnnHkHaKVbItYHR9WcD7vNqF2EE)

Thanks!!!
I got it working.
there are so much options to play with pfff haha.
i like this app more and more.

ok another question.
Can i set somehow that the app only record one timer?

when i export spreadsheet now, all timers are mixed up.
so for example:
i use timers for:
Cooking
Training
working
school stuff
etc.
If i export spreadsheet now, all these timers are mixed up in one tab in spreadsheet.
One big mess.

I don't want the app record every timer i use into spreadsheet.
What i want is to record one timer of choice and all other timers not.

Is this possible?

If not, than maybe is it possible that every timer has a separate tab in spreadsheet? (instead all timers in one tab)
Making categories of recordtag's doesn't do the trick sadly.

**Comment by xRahul** [comment]
@yourmother9 better to raise another issue for the next discussion. This issue itself can be closed as resolved.

**Comment by Razeeman** [comment]
@yourmother9 Unfortunately at the moment there is only a time range selection for csv export. Activities probably can be filtered in the spreadsheet editing program.

**Comment by yourmother9** [comment]
> @yourmother9 Unfortunately at the moment there is only a time range selection for csv export. Activities probably can be filtered in the spreadsheet editing program.

editing all saved timers in different categories its lots of work. 
what is the point to save all these timers mixed up in one tab in spreadsheet?
no one can work with that.

**Comment by cogk** [comment]
> what is the point to save all these timers mixed up in one tab in spreadsheet

Hey @yourmother9 :wave:, it's possible to separate the timers directly in the spreadsheet program, here it is in Apple Numbers and Google Sheets:

https://github.com/Razeeman/Android-SimpleTimeTracker/assets/10946971/e04ac950-6d13-42fc-a151-00bab0c0e01f

https://github.com/Razeeman/Android-SimpleTimeTracker/assets/10946971/586d33e8-a87d-4216-aca6-36070a223841

Similar features exist in other programs but I can't capture videos for them yet. You might want to look up “filtering rows” or “split data by value” in a search engine.

It's really easy to do in a spreadsheet program (a tool that is specialized in data processing), once learned, and there are many ways to do it. On the other hand it's hard to have it in an Android app (hard to code, hard to understand for users, might not cover all use cases, and is easily avoidable _feature creep_).
