### ISSUE TITLE
[Suggestion] Assign Record Tags to more than one activity

### ISSUE THREAD

**Issue by darkdecoy** [Razeeman/Android-SimpleTimeTracker#15]
I use the app to track my time at my job.  There are things that I do that we can bill to clients and things that we can't for any given activity so it would nice to be able create a record tag for billable and one for non billable and then assign it to multiple activities so that I start tracking I can select either the billable or non billable record tag.  Also I just want to say thanks for making such a great app.

**Comment by Razeeman** [comment]
Thank you for suggestion! I'm working on it at the moment, probably will be in the next update.

**Comment by Razeeman** [comment]
Was added in the latest update.
