### ISSUE TITLE
[Bug] ICS file export events UIDs are not consistent 

### ISSUE THREAD

**Issue by jlheflin** [Razeeman/Android-SimpleTimeTracker#154]
Hello! I have been using this amazing app for the past few days and honestly it is so feature packed that I just want to say thank you. I've noticed a small issue, when exporting the ICS file from the app, event UIDs are not consistent between exports. Here is an example from two exports of the same event:

Export 1:
```
BEGIN:VCALENDAR
PRODID:-//Simple Time Tracker//EN
VERSION:2.0
BEGIN:VEVENT
DTSTART:20240122T145000Z
DTEND:20240122T154000Z
UID:0287a093-18bf-4220-bee3-a58b29b1131a@stt
SUMMARY:CHEM 324
DESCRIPTION:Categories: Class, Work\nRecord tags: Class\n
END:VEVENT
```

Export 2:
```
BEGIN:VCALENDAR
PRODID:-//Simple Time Tracker//EN
VERSION:2.0
BEGIN:VEVENT
DTSTART:20240122T145000Z
DTEND:20240122T154000Z
UID:26b791a5-8997-4ae2-ba33-0b29146ccb86@stt
SUMMARY:CHEM 324
DESCRIPTION:Categories: Class, Work\nRecord tags: Class\n
END:VEVENT
```

I do not have much experience with ICS file formats, so this may not necessarily be a bug.

**Comment by Razeeman** [comment]
Hello! Thank you for pointing this out. I'm also not familiar this ICS so just made them unique on every export. Turns out this is not how it is supposed to be https://stackoverflow.com/a/25970005. Will try to fix this in the latest update.

**Comment by jlheflin** [comment]
Hey @Razeeman , I think I may have provided a way to solidify the UID, here is what I came up with, but I have never coded with Kotlin or Java so let me know if this doesn't work. I made changes to the IcsRepoImpl.kt file, let me know if you think this will work or not (also, if possible, I could also build it myself and see if it works but I am unsure of how to build apps):

Old Version:

```
return StringBuilder()
            .append("BEGIN:VEVENT\n")
            .append("DTSTART:${formatDateTime(record.timeStarted)}\n")
            .append("DTEND:${formatDateTime(record.timeEnded)}\n")
            .append("UID:${UUID.randomUUID()}@stt\n")
            .append("SUMMARY:${recordType.name.clean()}\n")
            .append("DESCRIPTION:$description\n")
            .append("END:VEVENT\n")
            .toString()
```

New Version:

```
return StringBuilder()
            .append("BEGIN:VEVENT\n")
            .append("DTSTART:${formatDateTime(record.timeStarted)}\n")
            .append("DTEND:${formatDateTime(record.timeEnded)}\n")
            .append("UID:${UUID.fromString(${recordType.name.clean()} + 
                    ${formatDateTime(record.timeStarted)} + 
                    ${formatDateTime(record.timeEnded)})}@stt\n")
            .append("SUMMARY:${recordType.name.clean()}\n")
            .append("DESCRIPTION:$description\n")
            .append("END:VEVENT\n")
            .toString()
```

The major limitation to this would be that exported ICS files would be dependent on the record name, start time, and end time of the event, meaning that any changes to these variables would cause a new UID to be present (maybe an underlying ID is generated for each category, which could then be used in UID generation, irrespective of category name changes?).

**Comment by jlheflin** [comment]
Hey Razeeman, I'm trying to understand the structure of the app a little better, I don't have any experience with android app development but I was going to try my hand at implementing this fix on my own. I was able to edit the ICS export file and have a build that produces consistent UIDs, but it is dependent upon the record name, the time started, and time ended. This isn't exactly useful, since it poses a lot of restriction on what you can do post export (if you change the times, it changes the UID), so my thought was to try and generate a random UUID for each record at creation and then get that UUID each time an ICS file is exported. 

My issue is that I don't really know where the Records are created in the app structure. If I knew where that was I could probably implement the UUID generation.

(This is mostly for my own fun, I don't necessarily think you'll be seeing a pull request from me but I think I can get it implemented.)

**Comment by jlheflin** [comment]
As of update 1.36 the issue seems to be fixed. Thank you!

**Comment by Razeeman** [comment]
Soory for the late reply. Yes, UID generation was changed in the latest release. Records are stored in the SQLite database, and there they have unique ids which conveniently can be used in the export.

Records are created here https://github.com/Razeeman/Android-SimpleTimeTracker/blob/448dc248962a048bbebe98633e886911d83edf2d/data_local/src/main/java/com/example/util/simpletimetracker/data_local/repo/RecordRepoImpl.kt#L120
through here
https://github.com/Razeeman/Android-SimpleTimeTracker/blob/448dc248962a048bbebe98633e886911d83edf2d/domain/src/main/java/com/example/util/simpletimetracker/domain/interactor/AddRecordMediator.kt#L14
