### ISSUE TITLE
bug counting hours

### ISSUE THREAD

**Issue by xunil89** [Razeeman/Android-SimpleTimeTracker#155]
on android 13 crdroid redmi note 9 pro with version 1.35(36) fdroid the app from a wrong hour count from 8:00 to 12:00 marks 3h59m if imposed 7:59 marks 4h
![Screenshot_20240202-211338_Simple Time Tracker](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/14961235/c5b0f533-dc18-4844-b2af-d6477e542bc6)

**Comment by DeDandeMan** [comment]
That's because it takes into account the seconds as well, your lavoro is probably a few seconds shy of being 4 hours long, hence the reason it shows as 3 hrs 59 min

**Comment by cogk** [comment]
To me it looks like the expected result: accuracy is important when talking about time :smile:

Could you send us the same screenshot with the `Show seconds` option turned on? Maybe there is a bug with the rounding but I don't believe so. The difference between _08:00:59_ and _12:00:00_ is 3h59m01s ~ **3h59m**.

**Comment by xunil89** [comment]
no longer to replicate it, it could be that actualmete pressed involuntarimete the -1s i don't know... also because the given time i had handed it.. .
