### ISSUE TITLE
[Feature] Move the Navigation Bar to the bottom of the app

### ISSUE THREAD

**Issue by DeDandeMan** [Razeeman/Android-SimpleTimeTracker#157]
I think it would be helpful if the navigation bar would be at the bottom of the screen to allow for easier switching between tabs

**Comment by cogk** [comment]
Note that it's possible to _swipe_ between pages

**Comment by DeDandeMan** [comment]
I know, but if I have to swipe between multiple pages, I prefer just tapping a button at the bottom

**Comment by chromer030** [comment]
+1 for bottom bar.

**Comment by chromer030** [comment]
+1 for bottom bar.

**Comment by Zolax9** [comment]
+1 would be nice as an option

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. Added an option to show nav bar at the bottom in the latest commits. Will be in the next update.

**Comment by chromer030** [comment]
@Razeeman 
You are doing great and you are a great man, thanks for all your efforts.
