### ISSUE TITLE
[Suggestion] Search for icons

### ISSUE THREAD

**Issue by WildOrangutan** [Razeeman/Android-SimpleTimeTracker#16]
I find scrolling through the icons a bit annoying. I would suggest implementing searching based on text keywords.

**Comment by dospes** [comment]
To add to this, I would also suggest that the current category of icons is highlighted in some way. I first though, that the "Editor" category was the active one, because of the grey bar under the pen.

**Comment by seefernando** [comment]
I'd also suggest persisting/freezing the Icons / Emoji selector when you scroll down the list, though it does reduce the available space.

**Comment by pragma-** [comment]
I was wishing for this while I was setting up my activities. +1

**Comment by pragma-** [comment]
I noticed that in the code for each icon entry, at least for the emojis, there is a trailing comment with the Unicode identifiers and description. A search and replace in some IDE or with `sed` to convert the comments into a quoted string as another field in the structure seems feasible enough, no?

**Comment by Razeeman** [comment]
Finally was able to implement it. Will be in the next release. Thank you for the suggestion!
