### ISSUE TITLE
why do timers count through when they have reached their goal? 

### ISSUE THREAD

**Issue by yourmother9** [Razeeman/Android-SimpleTimeTracker#166]
when i set a timer for 10 minute's or so... then when 10 min is over, timer keeps counting and not stop. 
this is useless, annoying, energy-consuming, etc. 
Where can i configure that it needs to stop when goal is reached?

**Comment by cogk** [comment]
If you want a timer, wouldn't it be better for you to use the built-in Clock app of the phone?

> useless, annoying, energy-consuming

Well it is none of those things when using goals for their intended purpose, that is helping you **limit** the amount of time spent on a task (like working X hours a day/week). In the end, this is a time tracking application, not a clock.

You wouldn't expect this behavior in a stopwatch, right?

**Comment by Razeeman** [comment]
Hello! Goals are meant to notify a user that they tracked some activity for a certain duration. After that it is for the user to decide, keep tracking this activity or switch to something else. Activity switching are meant to be done by hand. Hope this makes sense.
