### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by shlewislee** [Razeeman/Android-SimpleTimeTracker#167]
Are you willing to take donations? This is honestly one of the best FOSS Android app I use daily and I would like to make a little donation to thank you.

**Comment by Razeeman** [comment]
Hello! Thank you very much for the generous offer but this app is just a small hobby to switch gears from the main job. So no need for donations. If you want to help, may I suggest donating to some charity instead. ICRC would be my choice.

**Comment by Razeeman** [comment]
On the other hand I'm a little bit curious about maybe missing an opportunity for some additional financial support. Hope it wouldn't look bad if some day a link to buymeacoffee appear in the app, just to try it out.
