### ISSUE TITLE
[bug] Can't add statistics widget with 1.38 anymore

### ISSUE THREAD

**Issue by causa-prima** [Razeeman/Android-SimpleTimeTracker#168]
Short version:
When I try to add the "Statistics Chart" widget on my home screen, nothing happens after choosing the configuration I want, i.e. I get to the screen to configure the widget, but after I click "Save", nothing happens - the widget isn't added.

Long version:
It seems that the update to version 1.38 broke my widgets. I used both the "Single Activity" and "Statistics Chart" widgets on my home screen, and both just did not display anything anymore. Tapping them still lead to the expected action, i.e. tapping the "Single Activity" widget started the configured activity, but didn't display the timer and also didn't show the activity as active, and tapping the "Statistics Chart" lead to the right page in the app, but didn't show any data in the widget itself, not even after tapping the refresh button. Thus, I deleted both widgets and tried to re-add them to my home screen. This worked well for the "Single Activity" widget, but adding the "Statistics Chart" does not work as described in the short version above.

If you need any more infos, just let me know. I love the app and would be happy if this could get fixed.

Steps to reproduce:
1. Start adding the statistics widget to your home screen in the way your launcher wants you to do it (e.g. long-tap an empty space on your home screen) and select the "Statisitics Chart" widget.
2. On the widget configuration screen, make sure some activity is selected, and click "Save".

Expected behaviour:
The widget is added to the home screen as configured.

Actual behavior:
The widget is not added.

App version: 1.38 (installed from Google Play Store)
OS: LineageOS 21 (version "21-20240308-NIGHTLY-hotdog")
Launcher: LinageOS stock launcher
Phone: OnePlus 7T Pro (HD1913)

**Comment by Razeeman** [comment]
Hello! Sorry for the inconvenience. Can you please check previous version of the app? 1.37 for example or some older version, it is available here https://github.com/Razeeman/Android-SimpleTimeTracker/releases/latest

Not familiar with LineageOS, can you share is it a version of android 14? Checked on android 14 and widgets seems to be working. Also did not found any related to widgets changes in 1.38. Is it possible that the bug is related to the LineageOS update? `21-20240308-NIGHTLY-hotdog` seems like a very recent update.

**Comment by causa-prima** [comment]
I tried installing versions 1.37 and 1.36 by downloading the files "1.37-stt-rlease.apk" and "1.36-stt-rlease.apk" (the only apks on the release page for these versions, as far as I could find), but when I try to install them I just get a message "App not installed as package appears to be invalid".

Yes, LineageOS 21 is Android 14. As far as I remember, LineageOS is just AOSP with some additional features, and with optional google apps (e.g. play services etc.). I do have the usual Google apps installed (using the recommended MindTheGapp package). 

And you are right, it might be a LineageOS-update that broke this. I'm not completely sure when it happened, it might have been after the latest OS update. The updates are pretty frequent (weekly, I think), so I'll try again with the next version and check for related errors reports on the LineageOS-Side.

In the meantime, is there anything I could try to debug this further, e.g. active / check some (debug) log?

**Comment by Razeeman** [comment]
In order to install older versions, current version has to be uninstalled. If you would try this, make sure to create a backup file, so your data wouldn't be deleted. 

Unfortunately at the moment I'm not sure what could be done to investigate this bug.

**Comment by causa-prima** [comment]
Thanks, I uninstalled the latest version and tried with 1.37 - still, no change. Thus, you are probably right and this is a LineageOS issue. I created [a ticket on their side](https://gitlab.com/LineageOS/issues/android/-/issues/6911).

Still, thanks for the swift reply, great support and awesome app!

**Comment by Razeeman** [comment]
If I can help with anything feel free to reopen.
