### ISSUE TITLE
Not seeing Simple Time Tracker app in Samsung Galaxy Watch 4

### ISSUE THREAD

**Issue by teckwarz** [Razeeman/Android-SimpleTimeTracker#169]
I'm not able to find this "Simple Time Tracker" App when I search for this app in Play store in my Samsung Galaxy Watch 4. I could see wear os support has been recently added. Could anyone please clarify whether it is available for Watch 4.

**Comment by Razeeman** [comment]
Hello! It is currently under the review before being published. Commented here https://github.com/Razeeman/Android-SimpleTimeTracker/issues/60#issuecomment-1997052232

**Comment by Razeeman** [comment]
Should be available in the google play store now.
