### ISSUE TITLE
Romania translation

### ISSUE THREAD

**Issue by bnegrut** [Razeeman/Android-SimpleTimeTracker#170]
Hello,
Would you need a Romanian translation?

**Comment by Razeeman** [comment]
Hello! Of course, the more translations the better.

**Comment by bnegrut** [comment]
I suppose I need to create a new folder 'values-ro' under 'resources\src\main\res\' and I can use as source the English version in 'values'.
If yes, will get right on it.

**Comment by Razeeman** [comment]
That is correct. And if it is not too much, can you also create a new folder 'ro' under 'metadata' with files short_description.txt and full_description.txt, with the application description for the store.

Also can I mention you in the app as a translator and what name should be used for this?

**Comment by bnegrut** [comment]
Will do.
You can mention me as translator, You can Use Bogdan N

**Comment by bnegrut** [comment]
Done. Opened a pull request.
Adapted the Romanian full_description.txt to make a bit of sense. The source text: _Also widgets, backups, notifications and dark mode._
The Romanian adaptation would be translated in English as:  _The app has widgets, backups, notifications and dark mode._

**Comment by Razeeman** [comment]
Thank you very much for the help! Translation will be in the next release.

**Comment by bnegrut** [comment]
Thank you for the opportunity
