### ISSUE TITLE
Simple Time Tracker for macOS

### ISSUE THREAD

**Issue by teckwarz** [Razeeman/Android-SimpleTimeTracker#175]
Is it possible to build an app for this in Mac?

**Comment by Razeeman** [comment]
Hello! It is possible but I'm not familiar with the ios delevelopment and unfortunately do not have much free time at the moment. May be in the future.

**Comment by teckwarz** [comment]
Hi Razeeman, would you be fine, if I spend time to develop an app which could work in macOS. I'm expecting to provide very minimum functionality to only initiate and stop the tasks. This values would be synced with other devices. I'm asking to avoid getting distracted into doing other things in mobile while I'm doing something productive in the desktop. I have also never worked on MacOS apps, but since it is very useful app, I thought of taking this up. Do you have any documents where you could clarify how to contact the backend service to store the users tasks?

**Comment by cogk** [comment]
Hey :wave:

> Do you have any documents where you could clarify how to contact the backend service to store the users tasks?

There is no backend, I believe everything is stored locally in a SQLite database (via `androidx.room`), or in backups with a custom-made data format (see [BackupRepoImpl.kt](https://github.com/Razeeman/Android-SimpleTimeTracker/blob/dev/data_local/src/main/java/com/example/util/simpletimetracker/data_local/resolver/BackupRepoImpl.kt)) or various other formats, with remote backups possible too.

I think making a STT app for macOS would require some kind of syncing between the mobile and desktop apps. This might be difficult. However, it might be possible to "merge backups" and perform syncing this way, in a kind of "append-only" syncing, which is basic but work well for this kind of time tracking.

Maybe a first step would be macOS app that can generate Android STT-compatible backups, by keeping the same database definition, and possibly emitting the basic backup format.

_NOTE: It is not yet possible to import backups without deleting existing data._
