### ISSUE TITLE
[Feature Request] Ability to rearrange the activities

### ISSUE THREAD

**Issue by teckwarz** [Razeeman/Android-SimpleTimeTracker#177]
It would be better to have the ability to rearrange the activity tiles. I would like to order the activities based on the order I'll do the activities. Now the order is determined by the order in which I have created the activities in first place.

**Comment by Zolax9** [comment]
do you mean to arrange them manually?
if so, there is an option in Settings -> Display settings -> Sort activities (Manaully) to re-arrange them.

**Comment by teckwarz** [comment]
Thanks for replying. My current settings is already in manual. But I don't know how to trigger the rearranging of tiles. Please let me know if anyone knows how to trigger the manual drag and drop of activity tiles, long pressing edits the tiles.

**Comment by cogk** [comment]
@teckwarz Indeed it's not possible from the main activities list. In the settings, right besides the option ("Manually"), there is a cogwheel icon to tap (see picture below), which will open the list of activities where you will be able to reorder them by drag-and-drop.

![](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/10946971/7692a76e-bea5-485f-8654-44663c14c175)

**Comment by Razeeman** [comment]
The issue seems resolved, please reopen if it is not.
