### ISSUE TITLE
App build version for iPhone

### ISSUE THREAD

**Issue by gelavat** [Razeeman/Android-SimpleTimeTracker#178]
Hello.
This app is really great but I would need it for usage with an iPhone rather than on Android.
As this app is written in Kotlin, it is theoretically already fully ready to be built for iPhone with not much work and should be working out of the box.

Is this something that could be done?

It would be very much appreciated!
Thanks for any help.

**Comment by Razeeman** [comment]
Hello! Unfortunately it is not easy to convert android app into ios app. Even though it is written in kotlin, it would still require a lot of work. As I'm not familiar with ios development and do not have much free time at the moment, ios version is not planned. Maybe in the future.

**Comment by gelavat** [comment]
Hello Razeeman, thank you for answering.

Sad for this and that it is not so easy. Kotlin is advertised to be able to just change the destination platform, rebuilt and voila, but it seems then that it is not so true...
Anyways I think it would still be very useful for iPhone, because all those Time Tracker apps for iPhone are quite expensive and none matches simple features as your app and with local data storage and export.

I hope an iPhone dev could pass by, or maybe hiring one to do this porting job would be possible for quite little price, paid by someone or even by me. Maybe you have some devs you know that could do the job and provide info on how to pay them by someone passing by?

Thanks for this great app you provide, I am delighted!
