### ISSUE TITLE
[Feature Request] Show which activity a tag is (exclusively) assigned to.

### ISSUE THREAD

**Issue by th0b3n** [Razeeman/Android-SimpleTimeTracker#179]
When editing tags it is not immediately obvious, which activity a tag is assigned to. Currently the only hint seems to be the icon assigned to the activity, however, if two activities use the same icon, the assigned activity per tag is not visible.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. This would be in the next update.
