### ISSUE TITLE
recent comments by search are displayed with first comments first, not last comments

### ISSUE THREAD

**Issue by Zolax9** [Razeeman/Android-SimpleTimeTracker#185]
when editing an activity, searching for comments with the search comments feature displays the first comments first, rather than the last comments first.

there was a PR (#59) to fix this issue for recent comments in an activity (first displays when you edit an activity) but it seems this issue is now present for searching comments. I would write a PR for this, but I am not too sure what I would change to do so.

again, many thanks for the app! the last update was especially good (especially the custom icons, assigning tags to specific activities and assigning tags by default features!)

**Comment by Razeeman** [comment]
Hello! Makes sense. If "recent comments" are sorted by last first, maybe search results should be also. I'll look into it.

**Comment by Zolax9** [comment]
[it seems that you have fixed the problem.](https://github.com/Razeeman/Android-SimpleTimeTracker/commit/5c562eeb502156733ed15062398916140f88eece)

thanks! I will close this issue now.
