### ISSUE TITLE
Current activity notification disappers the moment I swipe away the app

### ISSUE THREAD

**Issue by ghost** [Razeeman/Android-SimpleTimeTracker#188]
Notification on the screenshot below disappears immediately after I swipe the app away (remove from recent apps).

My phone is Xiaomi Mi 9 (Android 11), every possible battery optimization is disabled. Notifications in other apps work fine, for example, Fossify Clock's stopwatch.

I am talking about this notification:

![Screenshot_2024-06-06-14-46-44-065_com razeeman util simpletimetracker](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/164055671/51147467-4ac8-4da8-9c0e-ce415905765a)

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. This is probably due to the extreme xiaomi battery optimizations. I also have a xiaomi phone and the only thing that helped is to keep the app in the memory, and pinning it so it won't be removed when clearing recent apps.
