### ISSUE TITLE
[Suggestion] Clone activity, multi select activities, add note/description for category tag activity, add notes

### ISSUE THREAD

**Issue by aleshanotdancer** [Razeeman/Android-SimpleTimeTracker#190]
- Can clone/duplicate activity to create other activity with same setting

- Can multi select activities in 'list activities screen' to: delete multi activities, add multi activities to category

- Add field for note add long text and style for category, tag, activity (not the comment)

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestions. Added an option to duplicate activity and add notes to activity / category / tag in the latest update. Multiselect is a bit difficult to intergrate into current UX so unfortunately will not be planned for now. Maybe in the future.

**Comment by TridentGalaxy** [comment]
@Razeeman Has the option to duplicate activities been removed since you posted this? I would find this option very useful.
