### ISSUE TITLE
[Feature request] Automate Activity with Broadcast Intents

### ISSUE THREAD

**Issue by MrGueest** [Razeeman/Android-SimpleTimeTracker#193]
Could you add a feature to automate Simple Time Tracker? I'd like to start an activity using a Broadcast Intent and stop it the same way. Also, please document how to use this.

**Comment by Mehlsine** [comment]
Hello MrGueest,

Have you checked "Automated tracking" section in Additional settings? This feature is present already, along with documentation on how to use it.

**Comment by Razeeman** [comment]
Seems resolved. Please reopen if it is not.
