### ISSUE TITLE
[Feature request] Relative mode for viewing statistics

### ISSUE THREAD

**Issue by pentergust** [Razeeman/Android-SimpleTimeTracker#195]
Hi, thanks for such a great app!

I like to view activity statistics to analyze what I've been doing lately. There is a very convenient view of statistics for the last 7 days. I would also like to be able to view statistics for longer time periods.

I understand that there is a view of statistics for a month, but it is not suitable if a new month begins.

**Comment by Razeeman** [comment]
Hello! Thank you for suggestion. Was implement in latest commits, will be in the next update. There will be an ability to select number of days for the "Last 7 days" range.
