### ISSUE TITLE
(Suggestion) Allow the day to end at a later time

### ISSUE THREAD

**Issue by ficion** [Razeeman/Android-SimpleTimeTracker#2]
Oftentimes apps of this kind allow the day to end at a later hour, such as 2 a.m., so activities that occur just after midnight are still included in the previous day. Hopefully this is not too complicated to implement!

**Comment by Razeeman** [comment]
Thank you for suggestion. It would be a useful feature. I'll think about how it can be implemented,

**Comment by bahalbach** [comment]
This is currently implemented.

**Comment by Razeeman** [comment]
Implemented in 1.16.
