### ISSUE TITLE
Translation german

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Razeeman/Android-SimpleTimeTracker#20]
is this app translatable ?

i can't do it with pull request, is there another way?
thanks in advance.

**Comment by Razeeman** [comment]
Hello! It is translatable. At the moment there are english, indonesian, russian, ukrainian and chinese translations.

If you wish to help with translation to some other language I would really appreaciate the help! I've compiled all the texts that are in the app at this moment in this file:
https://docs.google.com/spreadsheets/d/1xXngEXFIuVk_EH5sC76mE7ZI_xNbZwJq5xjoJsmkVZU/edit?usp=sharing

**Comment by mondlicht-und-sterne** [comment]
[STT ger texts.ods](https://github.com/Razeeman/Android-SimpleTimeTracker/files/7232019/STT.ger.texts.ods)

it is STT ger texts

i don't get on with google docs if you can't convert it. i never work with it.

or online:

https://docs.google.com/spreadsheets/d/1fFDkoDmWFco5k_7PPOIsahB_E5xUPAiTdKOLKIo4EQ4/edit?usp=sharing

**Comment by Razeeman** [comment]
German translation would be nice to have and ods file is fine, but I only see one page in this file, the one with the app description. There are two pages in the google sheets, first with description and second with texts. Am I missing something?

Also if you don't mind can I mention you in the app as a translator and what name would you like me to use for that?

**Comment by mondlicht-und-sterne** [comment]
the texts oh i see it. you become this in next days.

of cource you can mention me as a translator 
name: mondstern

**Comment by mondlicht-und-sterne** [comment]
@Razeeman 

https://docs.google.com/spreadsheets/d/1fFDkoDmWFco5k_7PPOIsahB_E5xUPAiTdKOLKIo4EQ4/edit#gid=4046959

[STT ger texts (1).ods](https://github.com/Razeeman/Android-SimpleTimeTracker/files/7239556/STT.ger.texts.1.ods)

**Comment by Razeeman** [comment]
Looks great! Thank you very much for the help. I'll add it as soon as possible and translation will be available in the next update release.

**Comment by mondlicht-und-sterne** [comment]
> Looks great! Thank you very much for the help. I'll add it as soon as possible and translation will be available in the next update release.

I'm glad.
If someone should translate even better, they are also welcome to do so.

**Comment by Razeeman** [comment]
Merged changes into dev, will be released with the next update. Thanks again for the help!
