### ISSUE TITLE
[FR] Add manual record using an Intent

### ISSUE THREAD

**Issue by saadulkh** [Razeeman/Android-SimpleTimeTracker#203]
This feature is about adding an additional intent to the existing supported intents to add a manual record automatically.

For example, given a start and end time through an intent, add a record to the list. Same as what we can manually do right now through the `+` FAB in records tab.

This helps greatly with off-device tracking like using IoT devices, and then seeing all the logs in one place.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback, seems like a useful feature. Start and end time that will be in the extras should probably be in the utc timestamp format. Will this be ok? Or some other format is preferred? For example yyyy-MM-dd HH:mm:ss

**Comment by saadulkh** [comment]
There can always be some preprocessing done at the automation app side. So, this app can expose whatever interface works for it. Like if the app is internally using UTC timestamps, then it can accept that format through intents, but works otherwise too. I would say just avoid introducing such complications for just this feature. Go with whatever is already being used.

`yyyy-MM-dd HH:mm:ss` is a good first choice. Obviously, the "best" format always depends upon user choice. For now we can just support one or 2 common ones, unless we get FRs for some specific formats. [Here](https://github.com/jameskokoska/Cashew/blob/5.2.3%2B328/budget/lib/struct/commonDateFormats.dart) is list of some common formats.

**Comment by dgudim** [comment]
+1 
Just commenting here to get notifications. My usecase is insertion of sleep activity after syncing with my watch

**Comment by Razeeman** [comment]
Added new action in the latest commits, will be in the next release.

<b>Action</b> - \"com.razeeman.util.simpletimetracker.ACTION_ADD_RECORD\" with extras: \"extra_activity_name\", \"extra_record_comment\", \"extra_record_tag\" and \"extra_record_time_started\", \"extra_record_time_ended\" in the format \"yyyy-MM-dd HH:mm:ss\" or UTC timestamp.

**Comment by saadulkh** [comment]
Thanks for your effort and great work. Appreciated.
