### ISSUE TITLE
App crashes phone

### ISSUE THREAD

**Issue by notawallheater** [Razeeman/Android-SimpleTimeTracker#206]
Don't know if this is the appropriate place to post, but the app seems to sometimes crash my phone since the last update. It has happened twice this week.
This is the first time ever I've had an app shut the phone down.

**Comment by notawallheater** [comment]
nvm, phone dying. happened in time tracker because it's the app I switch to most.

**Comment by notawallheater** [comment]
tried never leaving the app open to see whether it really was the phone. it's the app.

**Comment by notawallheater** [comment]
pretty sure it's a problem with archived activities. 
I had just archived ~10, app started shutting the phone down.
Unarchived them, everything seems back to normal.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback and sorry for the inconvenience.

- Can you please tell what do you mean by "shutting the phone down"? Do you mean the app crashes and phone shows home screen? Or the phone system restarts?
- Is there some error shown?
- Does it happen anywhere in the app or on some particular screen?
- Also can you please share your phones model and os version, maybe it will help identify the problem.

**Comment by notawallheater** [comment]
- phone restarts
- no error
- typically when I switch back to the app, or when I try to assign an activity to the last time block
- phone is: Xiaomi 11 Lite 5G NE; OS is 1.0.3.0.UKEUXM (Android 14 UKQ1.231108.001)

after unarchiving the activities, I had noticeably less crashes but had one happen just now. I'm probably going to stop tracking my time for a day or two (sad), to confirm gooder whether it's the app or something else.

**Comment by Razeeman** [comment]
Thank you for the information. Hard to tell what is causing this. Will keep looking at it. Also if you have any widgets of this app, it could help to try to remove them, maybe they cause something.

**Comment by notawallheater** [comment]
I have never used the widgets

**Comment by notawallheater** [comment]
Ok, I've uninstalled the app for a week or so, and the phone has crashed a couple times (instead of a couple times per hour). So I'm thinking the phone has a problem; and this problem is triggered by the app.
