### ISSUE TITLE
Show preview of selected records during data edit

### ISSUE THREAD

**Issue by Terrance** [Razeeman/Android-SimpleTimeTracker#209]
After you've set some criteria in the Data edit screen, you're told how many records will be affected by any edits, but it would be useful to actually have a visible list of them (or at least the latest ones if you don't want to potentially show thousands of matched records) for better sanity checking.

**Comment by Razeeman** [comment]
Hello! Records that are selected by the filter can be viewed by deselecting (not removing, but clicking on it again) a filter on the filtering screen. Same applies for the filter on the detailed statistics screen. Hope this makes sense.
<img width="426" alt="image" src="https://github.com/user-attachments/assets/7c0d72eb-59b6-4c67-a80e-8e99296f6261">

**Comment by Terrance** [comment]
Oh, so you can 🙂  That's not where I expected it to be, though it makes more sense now I know it's there!

Perhaps for new users it's worth drawing attention to the list being there somehow (unless I missed one already) -- a _deselect filter to preview_ hint or similar?

**Comment by Razeeman** [comment]
Agree that it is somewhat hidden, but also couldn't find a good way to show it without putting a hint. Somewhat oppose hints unless they are absolutely necessary because otherwise app would be full of hints :)

**Comment by Terrance** [comment]
Fair, there are quite a few other power features that could be similarly deserving of such hints...  ultimately solved for me now; hopefully if anyone else has the same question, they'll find their way here.  🙂
