### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Pyr0x1** [Razeeman/Android-SimpleTimeTracker#21]
Hello, I see italian translation is missing, could it be of any help? If yes, I can start working on it!

**Comment by Razeeman** [comment]
Hello! Italian translation would be very much appreciated. Can you make a PR or I can compile a file with all the texts for you?

**Comment by Pyr0x1** [comment]
I can open a PR, I just need a bit of guide on which file(s) to work on 😄

**Comment by Razeeman** [comment]
All the app texts are in the core/src/main/res folder. English is in the values/strings.xml file. For the italian translation you can create a "values-it" folder with the strings.xml file inside (analogous to other translations). Also app description is in the dev_files/publish folder, english is in the metadata.txt file.

**Comment by Razeeman** [comment]
Do you mind if I mention you in the app as a translator and what name would you like me to use?

**Comment by Pyr0x1** [comment]
Sure, you can mention me using my github nickname 😄 thank you!

**Comment by fabykr** [comment]
Hi there, does somebody already do a german translation? Otherwise, I could.

// Sorry, I should have looked first. It's already done :-D.

**Comment by Razeeman** [comment]
@Pyr0x1 Merged changes into dev, will be released with the next update. Thanks again for the help!

@fabykr Thank you very much for the suggestion but yes, german translation already added.
