### ISSUE TITLE
[Feature request] Spreadsheet Export to remember last used time range. Also to remember the last used csv file name

### ISSUE THREAD

**Issue by xged** [Razeeman/Android-SimpleTimeTracker#213]
Or a list of recently used time ranges

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Will a list of predefined ranges work? Something like this: Today, Last 3 days, Last 7 days, Last 30 days.

**Comment by xged** [comment]
@Razeeman For my specific use case - it should remember range start and give current time as range end. A list of multiple such options works too. Just 3, 7, 30 days etc would not work for me, although might be useful in the future.

**Comment by xged** [comment]
"This month" would work for me

**Comment by Razeeman** [comment]
"This month" is easier to implement. Thank you! Will work on this for the next update.

**Comment by Razeeman** [comment]
Added changes in the latest commits to save last selected time range and ability to change filename. Will be in the next release.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/eca600bf-a53c-4d3a-9b72-d3deabcdcc8d">
