### ISSUE TITLE
Option to activate/deactivate Do Not Disturb mode while clocked in

### ISSUE THREAD

**Issue by joeskeen** [Razeeman/Android-SimpleTimeTracker#214]
As a user, I would like to have certain time tracking activities automatically activate Do Not Disturb mode while tracking to comply with company policy or safe workplace requirements.

**Comment by Razeeman** [comment]
Hello! This could be done through the integration with third party automation apps like Macrodroid or Tasker. Time tracker app can send an event to these apps when some activity is started, and these apps could react to these events by enabling or disabling do not distiurb mode. 

Hope this make sense.

**Comment by joeskeen** [comment]
Great idea! I'll have to try it out!

**Comment by StanczakDominik** [comment]
I'm pretty sure this one could be closed - it's exactly what Tasker and the like were made for :)

**Comment by Razeeman** [comment]
Probably could be closed, please reopen if you have any more questions.
