### ISSUE TITLE
Copyable Automated Tracking Intents Details

### ISSUE THREAD

**Issue by PazerOP** [Razeeman/Android-SimpleTimeTracker#216]
Would be great if the "Automated Tracking" documentation popup had selectable/copyable text, so you don't have to retype the intents by hand into tasker etc.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion, it will be useful indeed. Will try to look into it.

**Comment by Razeeman** [comment]
Will be in the next release.
