### ISSUE TITLE
Ability to backup setting.

### ISSUE THREAD

**Issue by krishnakanthb13** [Razeeman/Android-SimpleTimeTracker#219]
**Ability to backup settings.**

1. Backup Icon/Emojis and Color selections for tasks.
2. Backup Icon/Emojis and Color selections for tags.
3. Icon/Emojis and Color selections for categories.
4. All the options in the Setting Tab.

This way it will be very helpful when moving from one phone to the other.

**Purpose:** When moving from one phone to the other, it should just replicate the complete set up from the old phone or backup phone. The process should be very seamless. (A replica of the current app!).

**Comment by cogk** [comment]
> 1. Backup Icon/Emojis and Color selections for tasks.
> 2. Backup Icon/Emojis and Color selections for tags.
> 3. Icon/Emojis and Color selections for categories.

Hey :wave:, aren't those settings already backed-up? What version are you using currently?

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. 1-2-3 should be already in the backup. Adding settings into backup file is planned for future release but can't tell for sure when it will be implemented.

**Comment by sreich** [comment]
I'm curious what the code currently does, (please correct my rusty Android) but I thought using the newer APIs for settings/views, would automatically also give you persist to disk ability, and take advantage of the automatic android facilities

**Comment by Razeeman** [comment]
Added settings to the backup file. Restoring settings will be available as a separate option. Will be in the next release.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/3e121c62-4d53-44dc-af37-0ce166efb386">

@sreich Hello! Automatic android backup "should" "probably" work :) But I never used it myself, so wouldn't count on it, better to be safe and include all data in the backup file.
