### ISSUE TITLE
Dont reset series to 0 until the end of the day when you know for sure it didnt happen

### ISSUE THREAD

**Issue by voidplayer** [Razeeman/Android-SimpleTimeTracker#223]
I dont see my current streak until i do the task because app assumes that if you didnt do it yet you are not going to make it

I suggest showing the current streak instead of 0

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Makes sense, will try to implement it.

**Comment by Razeeman** [comment]
Will be in the next release.
