### ISSUE TITLE
Multiple tags in the intent?

### ISSUE THREAD

**Issue by dgudim** [Razeeman/Android-SimpleTimeTracker#227]
Sorry if this is possible already, but I couldn't figure out how to start an activity with multiple tags from tasker.

Adding 2 extras for tags just uses the last one

**Comment by Razeeman** [comment]
Hello! Unfortunately it is not possible at the moment. Will try to add it in the next release or the one after the next. Probably will add ability to pass list of tags names as a comma separated string.

**Comment by Razeeman** [comment]
Added in the latest commits, wil be in the next release. Thank you for the feedback!

**Comment by dgudim** [comment]
Thank you for the great work!
