### ISSUE TITLE
Flash of incorrect style in dark mode

### ISSUE THREAD

**Issue by quartertone** [Razeeman/Android-SimpleTimeTracker#229]
Launch screen (splash screen) style does not change according to app theme, so in dark mode there is a flash of light theme when the app is first started (or opened via the "universal" widget).

To reproduce: 
1. Set app to Dark theme
2. Close app and remove from recent app list 
3. Start app

**Comment by cogk** [comment]
On my phone it always shows the light-themed splash, is there even a dark-themed splash animation?

**Comment by cogk** [comment]
This has been fixed in the latest release

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. This indeed should be fixed in the latest release. Splash screen should now follow the system theme, so if the system is in the dark mode and the app is in the dark mode, there shouldn't be a white flash on app start. Please reopen the issue if it is not fixed.
