### ISSUE TITLE
[Feature request] Alongside each "save" button, make a "share" button

### ISSUE THREAD

**Issue by xged** [Razeeman/Android-SimpleTimeTracker#231]

**Comment by Razeeman** [comment]
Hello! Can you explain a little bit what would this feature do?

**Comment by xged** [comment]
@Razeeman  Im sending the data to my Whatsapp on the computer to processes it

**Comment by Razeeman** [comment]
Can you please explain which "save" buttons are meant and which data would be sent via sharing? Is it about backup files?

**Comment by xged** [comment]
spreadsheet export

**Comment by Razeeman** [comment]
Implemented in the latest commits, will be in the next release. Share button would be available after saving the file. Probably not the most convenient solution but was fastest to implement.

<img width="394" alt="image" src="https://github.com/user-attachments/assets/c29e1ae2-2b72-4a78-9a8e-7921a42b1de7">
