### ISSUE TITLE
CSV export for activities with quotes in their description

### ISSUE THREAD

**Issue by artiekra** [Razeeman/Android-SimpleTimeTracker#236]
*I am on version 1.46*

When exporting in CSV format, double quotes in activity descriptions and similar places should be replaced/escaped with `""`. Not all the parsers would still be able to read the data properly, but that seems to be the most commonly used solution.

Example of how the data is being currently exported:
![image](https://github.com/user-attachments/assets/624ee7cf-59ea-4f7c-89b7-61b384566d02)
![image](https://github.com/user-attachments/assets/ab3cdb21-17d1-40b5-96cf-b815ddade7b3)

Sorry if I'm missing something - it doesn't seem there are any already opened issues on this topic, maybe this was fixed after the latest release?

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. Didn't know that qouble quotes should be escaped with double quotes in csv. Fix will be in the next release.
