### ISSUE TITLE
[help] receiving events/intents from STT (MacroDroid)

### ISSUE THREAD

**Issue by Zolax9** [Razeeman/Android-SimpleTimeTracker#239]
hello! I'm trying to receive an intent on MacroDroid (eg. started activity) but the trigger isn't being triggered when I actually start the activity.
is this config correct? there are no extras in the trigger, either.

![1](https://github.com/user-attachments/assets/30bf8543-d075-40ac-b9fc-fdb8763af0b8)

thanks again for STT!

**Comment by Razeeman** [comment]
Hello! Can you please check that the "Send events" option is enabled? Other than that it should be working.

**Comment by Zolax9** [comment]
> Hello! Can you please check that the "Send events" option is enabled? Other than that it should be working.

nevermind, looks like none of the triggers work for MacroDroid. the same example works fine with Automate. thanks for the help though!

**Comment by Mehlsine** [comment]
Tried to reproduce your settings. Works just fine for me.
One UI 6.1, Android 14

https://github.com/user-attachments/assets/72428fd7-a3d9-474e-9fc4-7a1a338dc491
