### ISSUE TITLE
[Suggestion] Reminder notifications at a regular interval even when activity is running

### ISSUE THREAD

**Issue by edelgrace** [Razeeman/Android-SimpleTimeTracker#24]
Sometimes I find that I leave an activity running and later I realize I forgot to change what I was doing. Right now my solution is to have another app beep at me every 15 minutes and I have to remember that means "what are you doing" right now and go to the app.

I think also having an option to have a time range to turn off these notifications (like while sleeping) would be beneficial.

**Comment by Razeeman** [comment]
Hello! Sorry for the late response. I've added Activity reminder in the latest commits, it should be in the next update. It will work same way as Inactivity reminder but when some activity is being tracked. Also there would be a Recurrency option and Do not disturb option.
