### ISSUE TITLE
[Suggestion] Scrolling should stop when selecting an icon category

### ISSUE THREAD

**Issue by dospes** [Razeeman/Android-SimpleTimeTracker#25]
When scrolling through the list of icons and tapping a category, the icons keep scrolling. In my opinion the scrolling should stop, when a category is selected.

**Comment by bahalbach** [comment]
In my opinion I like being able to keep looking through the available icons, but this seems like a spot for a preference in settings.

**Comment by Razeeman** [comment]
Was implemented in the latest update. Thank you for the suggestion.
