### ISSUE TITLE
Combine recent comments and comment search on entry edit

### ISSUE THREAD

**Issue by Terrance** [Razeeman/Android-SimpleTimeTracker#256]
When editing an entry's comment, the comment field can be in two states:

* _Enter new comment_, with _Last comments_ below showing recent but unique comments for the selected activity
* _Search comments_, with search results of recent comments (including duplicates) across all activities

I seem to regularly hit a couple of minor UX pain points with this;

* Duplicate search results makes it harder to find what you're looking for (with nothing other than the comment here, there probably isn't any need to show the same comment more than once, so these ought to just be deduped).
* If I don't find what I want, it's not entirely obvious the comment field is in search mode, and submitting with the desired comment in the showing field gets lost because the hidden field's value is taken instead.

I would propose combining these two modes and removing the search toggle, so that recent comments are shown when the field is empty, and they're effectively filtered (as is currently done with search mode) as you type your comment.  I'm not sure I've needed to search for comments here from a different activity, but that could still be used when searching on the assumption that it'll soon drill down to the desired text.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Makes total sense. Will be in the next release.

**Comment by Terrance** [comment]
Got the update a couple of days ago; having been playing with this for a bit now, I think this works a lot better -- thanks!

Favourite comments also looks handy, though for me at least it's hindered somewhat because they apply globally (I tend not to use many comments the same across multiple activities) -- I'd find it more useful if they were also filtered to comments only used in the currently-selected activity, but I don't know if I'm the minority here, and the choice of recent comments usually has what I'm looking for in any case.
