### ISSUE TITLE
No button to close tag selection dialog feels unintuitive. 

### ISSUE THREAD

**Issue by bahalbach** [Razeeman/Android-SimpleTimeTracker#28]
When starting an activity with the setting "Show record tag selection" set a full screen dialog for record tag selection will open. If "Close after selecting one tag" is not set, then you can only close the dialog by pulling it down or pressing back. Both of those feel like I'm canceling the tag selection instead of confirming it. Something like a "Save" button at the bottom would feel more like saving the tag selection.

**Comment by Razeeman** [comment]
Thank you for the suggestion. That's true. And closing the dialog by pulling or pressing back probably should actually cancel tag selection and don't start timer. Need to work on that.

**Comment by Razeeman** [comment]
Changed in latest commits.
