### ISSUE TITLE
[Suggestion] Add notification for running activities

### ISSUE THREAD

**Issue by yegarti** [Razeeman/Android-SimpleTimeTracker#3]
Hi,
Sometimes when I start an activity I forget to end it.
I think it could be nice to add a permanent notification when an activity has started with an option to end it from the notification menu.

Thanks.

**Comment by Razeeman** [comment]
Hello! Permanent notification when activity is running can be enabled from the settings screen. Ability to stop timers from this notification could be a nice feature, thank you for suggestion.

**Comment by Razeeman** [comment]
Stop button was added in the latest commits. It will be in the next release.
