### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [Razeeman/Android-SimpleTimeTracker#32]
Could you please publish your app on F-Droid? Thanks!

**Comment by linsui** [comment]
@Razeeman Can I package this app for F-Droid?

**Comment by d1nuc0m** [comment]
Up, it would also be useful for those who don't use the Play Store

**Comment by kmantel** [comment]
+1 to this suggestion as well. I first searched on f-droid for an app like this before resorting to the play store.

**Comment by Razeeman** [comment]
@linsui Hello! Sorry for the late reply. Can you help with the packaging? I've added fastlane metadata. Not sure about the next step.

**Comment by linsui** [comment]
Done, thanks! The next step is add the F-Droid badge ;). See https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md.

**Comment by Razeeman** [comment]
@linsui Thank you very much for the help!
