### ISSUE TITLE
[Suggestion] Keep screen on option

### ISSUE THREAD

**Issue by evrenckn** [Razeeman/Android-SimpleTimeTracker#33]
Hi, I'm using this app as focus timer while i'm studying so it'd be nice to have an option in settings to "keep screen on".

A full screen page with running record info and bigger timer like focus timer apps would be even nicer (maybe triggered by swiping a running record), but "keep screen on" option is simpler to implement i guess.

I hope you consider it.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Bigger timer is an interesting idea but a setting to keep screen on is indeed simpler to implement at this moment. I've added it in the latest commits, will be in the next update.
