### ISSUE TITLE
[Suggestion] preserve linebreaks in exported records comments

### ISSUE THREAD

**Issue by cogk** [Razeeman/Android-SimpleTimeTracker#34]
Could there be a way to preserve the line-breaks of the records' ***comment*** field while exporting to a CSV file (“spreadsheet export”), and maybe to a STT file?

----

Most CSV parsers and spreadsheet apps can read multiline strings (wrapped in quotes) from CSV files.

Therefore a change like proposed below could be enough to allow line-breaks in the CSV export:

```diff
String.format(
-   "%s,%s,%s,%s,%s,%s\n",
+   "%s,%s,%s,%s,%s,"%s"\n",
    ...
-   record.comment.clean(),
+   record.comment,
```
https://github.com/Razeeman/Android-SimpleTimeTracker/blob/fd3d79164e84c34ed5426bdeb2952b7949c83373/data_local/src/main/java/com/example/util/simpletimetracker/data_local/resolver/CsvRepoImpl.kt#L97-L102

----

For the STT backup/restore, it might be too much work. Maybe the `clean` method could replace `[\n\t]` by some kind of [sentinel value](https://en.wikipedia.org/wiki/Sentinel_value) like `<|eol|>` or `␤`? but that feels like a hack…

https://github.com/Razeeman/Android-SimpleTimeTracker/blob/fd3d79164e84c34ed5426bdeb2952b7949c83373/data_local/src/main/java/com/example/util/simpletimetracker/data_local/resolver/BackupRepoImpl.kt#L212

https://github.com/Razeeman/Android-SimpleTimeTracker/blob/fd3d79164e84c34ed5426bdeb2952b7949c83373/data_local/src/main/java/com/example/util/simpletimetracker/data_local/resolver/BackupRepoImpl.kt#L326

https://github.com/Razeeman/Android-SimpleTimeTracker/blob/fd3d79164e84c34ed5426bdeb2952b7949c83373/data_local/src/main/java/com/example/util/simpletimetracker/data_local/resolver/BackupRepoImpl.kt#L279

*Thank you for your time.*

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Preserving line breaks in comments in csv export and in backup file was added in the latest commits. Will be in the next update.
