### ISSUE TITLE
[Suggestion] Changing the record tag separator for .CSV exports

### ISSUE THREAD

**Issue by ghost** [Razeeman/Android-SimpleTimeTracker#39]
When exporting records that contain multiple record tags, the corresponding field on the .CSV file consists in a space-separated list of tags.

This can lead to problems when using tags that contain spaces (as I found out the hard way).

Changing the separator to a comma or adding an option to allow the user to select their own separator or format for the field would be very helpful for those who end up having this issue.

When I'm back home I'll add concrete examples of this issue to the thread.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Added comma separator to record tags in the latest commits. Will be in the next update.
