### ISSUE TITLE
Support emojis as icons

### ISSUE THREAD

**Issue by tomzx** [Razeeman/Android-SimpleTimeTracker#4]
Hello!

First I'd like to thank you for this wonderful app, it fits my need to track time perfectly.

It would be awesome if we could use emojis as icons. While the current set of icons is great, I think the set of emojis might cover a larger set of possible icons, while also providing text search when selecting which emoji to pick. Furthermore, this would allow for a bit more color than the white icons.

Thanks!

**Comment by tomzx** [comment]
Thanks a lot for the addition of emoji support in 1.11. :tada: 

My only remaining ask regarding this feature would be to be able to type to search the emoji instead of having to scroll through the list, especially when I don't know where the icon is :joy:.

**Comment by Razeeman** [comment]
Hello! Thank you for suggesting emojis support. Search would a useful feature indeed, but I'm not sure how to implement it correctly at the moment, because as I can see, search is only can be possible by typing in english, which would be a little counterintuitive in other languages.

**Comment by tomzx** [comment]
My initial thought was that it would be possible to invoke the emoji keyboard which supports search. This way we would delegate the task of displaying the emoji list and searching them to the keyboard/OS.

**Comment by Razeeman** [comment]
In the latest update I've added ability to use text as icon, and it is also possible to use emojis there and also search for emojis.
