### ISSUE TITLE
[Suggestion] Auto Export on selected periods

### ISSUE THREAD

**Issue by mertbakir** [Razeeman/Android-SimpleTimeTracker#40]
Hi,

I have a suggestion and it would be really helpful for me if you could add an option to export data (as .csv) to a selected path in selected time intervals. It would be even better if you can make the range to be exported selected by the user. Either last data that is not exported or whole data. 

- Every week on monday 00:00, export the data of last 7 days.
- Every week on monday 00:00, export whole data.

**Comment by neekubee** [comment]
Can an app like this do an automated task that needs storage permissions to happen? Is your workaround a recurring task in a to do app or an alarm on your mobile?

**Comment by mertbakir** [comment]
I think it should be because Aegis, another android app I use, can export a json automatically, it's not on schedule though. Of course it asks for storage permission for a specific folder.

I have no workaround, just casually exporting data time to time.

**Comment by Razeeman** [comment]
Implemented in the latest release. Thank you for the suggestion.
