### ISSUE TITLE
[Suggestion]Longclick item on record list provide delete option

### ISSUE THREAD

**Issue by fairyex** [Razeeman/Android-SimpleTimeTracker#42]
It would be much easier to manage a record if there is a delete option when user longclick a item on record list.

**Comment by Razeeman** [comment]
Hello! Sorry for the late reply and thank you for the suggestion, but I think it would need a confirmation after long click and I'm not sure that a long lick on record and another click to confirm would be easier than just click on record and click on delete button. Correct me if I'm wrong.
