### ISSUE TITLE
[Suggestion] [Feature] Goal time can be extended to weeks or month 

### ISSUE THREAD

**Issue by gpsarathy** [Razeeman/Android-SimpleTimeTracker#43]
As per the current model, I can set goal for activity that'll display/notify based in a single day activity duration.
If that can be extended for weekly/monthly goal time, User can efficiently plan or catch up for the accumulated duration on the planned week.

>It'll be a great feature, one of the important one among similar apps. Great app team ! ❤️

**Comment by gpsarathy** [comment]
This has been addressed, however monthly goal is not added. However, using report it can be tracked indirectly. We can close this if this request outdated

**Comment by Razeeman** [comment]
Monthly goal probably will be added in the next update.
