### ISSUE TITLE
[Suggestion] Quick tile or Notification to start activity.

### ISSUE THREAD

**Issue by KAGEYAM4** [Razeeman/Android-SimpleTimeTracker#44]
First of all thank you for this great app.
Now, A permanent notification or a quick tile option to start a activity would be awesome. It will reove the hassle of opening the app and then starting a activity.

**Comment by Razeeman** [comment]
Hello! There are widgets that can start and stop activities without opening the app. Is this what you looking for?

**Comment by KAGEYAM4** [comment]
@Razeeman  Yes i saw this , its great. But is there are other ways like hidden way. Like i use tasker and gesture app , any way to trigger through them .. i want my homescreen to be empt ( using a setup kwgt) , or a notication - which on cick will overlay activities to start or stop. Or some other way which you think will be great ..

If its no then its good too, the app is great overall.

**Comment by ColdHotman** [comment]
@Razeeman

I'm imagining a Quick Settings tile, allowing quick and easy access i.e. start/change individual activities, pause timer etc. It's the buttons that show up when you pull down in the notification panel.

I think it sound like a great idea.

**Comment by Razeeman** [comment]
@PhoenixCODE2322 
I've added integration with tasker. It will be in the next update. Will it help with your issue? Also there is one tile widget that can start \ stop any activity.

**Comment by Akrai** [comment]
Can you implement a permanent notification with buttons for start and stop task tracking without having to unlock the phone?

**Comment by Razeeman** [comment]
Thank you all for suggestions! In the latest update I've added ability to change activities from the notification timer.
