### ISSUE TITLE
[Feature] List tags closer to bottom of screen for better reachability

### ISSUE THREAD

**Issue by preethamrn** [Razeeman/Android-SimpleTimeTracker#45]
In previous versions of the app, swiping down on the screen which asks "Select record tag" would automatically start the record with Untagged. However now, you need to manually select untagged for the record to start. This isn't very ergonomic and the app's UX could be improved by moving the tags at the bottom of the screen instead of near the top.

Preferences:
* Show record tag selection: true
* Close after selecting one tag: true (if this is false, then even selecting untagged does not start the record)
* Allow multitasking: false
* (other preferences do not seem relevant however I can add those as well if needed)

**Comment by Razeeman** [comment]
Thank you for the suggestion. Tags was moved closer to bottom in the latest update.
