### ISSUE TITLE
Enable backups for this app

### ISSUE THREAD

**Issue by Zocker1999NET** [Razeeman/Android-SimpleTimeTracker#50]
https://github.com/Razeeman/Android-SimpleTimeTracker/blob/893700c0db89fe8bbc147e5ab3ee621f9c80484b/app/src/main/AndroidManifest.xml#L7

Is there a good reason for why backups are disabled? I would like to have the content of this app backed up properly because it isn't synced away automatically anywhere.

I didn't found any issue where this was already discussed, so I thought to ask.

**Comment by neekubee** [comment]
I have the latest android version (v1.19). I can backup just the same (json and csv). You still can't?

**Comment by Razeeman** [comment]
@Zocker1999NET Hello! Thank you for pointing this. I don't think there was a good reason, probably will change this in the next update.

**Comment by Zocker1999NET** [comment]
> @neekubee: I have the latest android version (v1.19). I can backup just the same (json and csv). You still can't?

I think you speak about manual backuping. I speak about the integrated backup system of Android (used by Google, Samsung, some other OEMs or [Seedvault](https://github.com/seedvault-app/seedvault)). I can manually back up my records just fine (that's how I moved them from my old phone to my new one). But it does not happen automatically, which is not good, because you can (I definitely will :laughing:) forget it.

**Comment by Razeeman** [comment]
android:allowBackup was set to "true" in the latest commits. Will be in the next release. Thanks again!

**Comment by Zocker1999NET** [comment]
Thanks for that & anyway thanks for this great & simple app
