### ISSUE TITLE
Add ability to save the location

### ISSUE THREAD

**Issue by Myzel394** [Razeeman/Android-SimpleTimeTracker#54]
It would be nice to be able to see the location of where you tracked your data. This should be opt-in in my opinion

**Comment by S5E5S** [comment]
I think the general label could be used for that purposes.

**Comment by Razeeman** [comment]
Hello! Seems like tags can be used for this or some integration with apps like Tasker. Adding geolocation tracking is out of scope of this app because of required persmissions.
