### ISSUE TITLE
Database synchronization

### ISSUE THREAD

**Issue by 1over137** [Razeeman/Android-SimpleTimeTracker#55]
It would be great if the database is accessible in the filesystem, so it can be synchronized with another device (or computer, for the purpose of backing up) in real time.
It would also be great if there is support for performing some network function when you track something, such as POSTing a json to a remote server.

**Comment by Razeeman** [comment]
Hello! Seems like accessible database would contradict with android security. Tasks like triggering some REST api probably can be done by apps like Tasker.
