### ISSUE TITLE
[Feature] Add untracked to previous entry

### ISSUE THREAD

**Issue by pat-richter** [Razeeman/Android-SimpleTimeTracker#57]
User Story: I'm writing a Feature Request. I think I'm done. I'm clicking the Untracked entry, choose an activity, save. A minute later I have something which needs to be considered, too. I think I'm done. I'm clicking the Untracked entry, choose an activity, save. 

---

It's not a big issue, but a button on an untracked entry could easily merge it with the previous entry. 3 clicks and 10 seconds saved.

**Comment by Razeeman** [comment]
Thank you for the suggestion. I've added some actions for editing record, and where would be a merge option for the untracked time. It will be in the next update.
