### ISSUE TITLE
[Feature] Autosuggest "latest" and "user defined" comments

### ISSUE THREAD

**Issue by pat-richter** [Razeeman/Android-SimpleTimeTracker#58]
User Story: I restart a task after taking a break. After finishing it, I have want to add a comment. It's the same comment as before, but I have to type it again.

***

I would like to have a small storage of comments, which become visible while typing.

1\. "The x latest" comments
   - There should be a setting "how many should be stored", 0 disables the feature

2\. "User defined" comments
  - There should be an editable list of comments

**Comment by Zolax9** [comment]
commit d6026e1 should be able to show the latest comments through the "Last comments" section.

**Comment by Razeeman** [comment]
Hello! There is a feature similar to this, latest comments. It shows a fixed number of last entered comments for this activity. It's not exactly what you are suggesting, but it works for this user case.
