### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [Razeeman/Android-SimpleTimeTracker#6]
Just wondering whether you could point out what license your app is under? And while on it: did you consider making the app available outside of Google's walled garden – for those with no Google account and those using Google-free devices?

**Comment by Razeeman** [comment]
Hello!
I'm not yet sure what license to choose. At the moment where is no license meaning the default copyright rules apply
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license
About different market - thank you for the suggestion, I'll think about it!

**Comment by IzzySoft** [comment]
Ah, didn't know about that license list. Not really appropriate, though, as several of those licenses are not really suited for code/apps (and they lack some explanation on them). May I recommend you the [SPDX license list](https://spdx.org/licenses/) and concentrating on those licenses approved by both, FSF and OSI? Depending if you want it to be least restrictive (Unlicense, Apache, MIT) or rather more copyleft (AGPLv3, GPLv2/3), you have a full range there. I personally would go for AGPL or GPLv2, but those are my personal preferences – YMMV. But no license mentioned usually means "all rights reserved", AFAIK :wink: – ah, I see that's what Github also says. They link to chooseALicense, which is not bad – but I found it hard to work with that (quite limited choices and not always the best – where OTOH SPDX might appear overwhelming).

Having such an "approved" license would e.g. be one pre-condition for getting your app listed on [F-Droid](https://f-droid.org/) or with [my repo](https://apt.izzysoft.de/fdroid). For starters, you could [tag your releases](https://github.com/Razeeman/Android-SimpleTimeTracker/releases) and attach the APK to its corresponding release. This is what many projects do, so at least the APK is available (though not really in an end-user friendly way). Again, tags would be needed for F-Droid – and the APK for my repo (which has less strong inclusion criteria).

**Comment by IzzySoft** [comment]
Any news, @Razeeman?

**Comment by Razeeman** [comment]
Added a GPLv3 license.

**Comment by IzzySoft** [comment]
Thanks @Razeeman! Any pointers regarding the second part (tags, APKs)?

**Comment by Razeeman** [comment]
Thank you for the suggestion. I've added previous releases for posterity as well as the latest release.

**Comment by IzzySoft** [comment]
Thanks a lot! You've just established 2 new contribution channels :smiley: One is the APKs at your releases (already available since 2h ago), the second is via my repo, where [your app will show up](https://apt.izzysoft.de/fdroid/index/apk/com.razeeman.util.simpletimetracker) with the next sync tomorrow around 6:45pm UTC :partying_face: :tada: so folks can use the F-Droid client to install it and keep it updated.

Looks good btw. Should you decide one day you want it in the [F-Droid repo](https://f-droid.org/) itself, I gladly assist with that. A first step to that would be establishing [Fastlane structures](https://gitlab.com/snippets/1895688), for which I could provide a "starter package" as PR if you want (as I've established them locally for my repo already).
