### ISSUE TITLE
NFC feature

### ISSUE THREAD

**Issue by SirLouen** [Razeeman/Android-SimpleTimeTracker#66]
I've seen that this app supports NFC tags but I'm not 100% confident how to set this up. 

How can I target this package? Any recommended app for this purpose?  For example, with Tasker, I don't see an action that permits querying a package with an action

**Comment by Razeeman** [comment]
Hello! I'm not using this feature but it should work with third-party apps that can send intents or broadcast intents. For example Tasker: https://tasker.joaoapps.com/userguide/en/intents.html

**Comment by Razeeman** [comment]
Also MacroDroid seems like a good and free alternative. #68

**Comment by joshinils** [comment]
> Also MacroDroid seems like a good and free alternative. #68 

Not anymore
