### ISSUE TITLE
[Suggestion] CSV export: add time spent field

### ISSUE THREAD

**Issue by rudolfmu** [Razeeman/Android-SimpleTimeTracker#67]
Please add a time spent field to the exported .csv. You calculate it anyway when you display the list, so adding that to the .csv would be nice. Else for accounting many people need to extra calculate that after importing elsewhere, as you only put start and end times in the .csv. A single field with the rounded up minutes would suffice.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. I'll add it in the next release. Format would be like "hh:mm:ss" for example "01:30:00" as it seems to be a spreadsheet's format for duration.

**Comment by rudolfmu** [comment]
Thank you for your quick response.
There is s duration functioning in excel. But that is a complicated financial function. I found no easy way to use 01:30:00 for accounting. It would me easy to to accounting on spent time if you could supply the amount of minutes rounded up as one value.
Thanks, Rudolf.

Am 20. Januar 2023 09:26:44 UTC schrieb Anton Razinkov ***@***.***>:
>Hello! Thank you for the suggestion. I'll add it in the next release. Format would be like "hh:mm:ss" for example "01:30:00" as it seems to be a spreadsheet's format for duration. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Razeeman/Android-SimpleTimeTracker/issues/67#issuecomment-1398125357
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Razeeman** [comment]
This representation can be switch in spreadsheet to number value and it will represent a portion of 24 hours, for example "01:30:00" would be 0.0625, by multiplying it by 24*60 a number of minutes can be found out. Can this be acceptable for your usecase or a number of minutes still would be better?

**Comment by rudolfmu** [comment]
As far as I have found out, only Apple Numbers will accept this format. Excel and its clones need to apply functions to isolate hours and minutes and and then calculate. For most accounting, the total minutes would be the easiest, as a numeric string can be directly used. The seconds don't matter as this is not used as a stopwatch.
Thank you for caring!

Am 23. Januar 2023 13:29:20 UTC schrieb Anton Razinkov ***@***.***>:
>This representation can be switch in spreadsheet to number value and it will represent a portion of 24 hours, for example "01:30:00" would be 0.0625, by multiplying it by 24*60 a number of minutes can be found out. Can this be acceptable for your usecase or a number of minutes still would be better?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Razeeman/Android-SimpleTimeTracker/issues/67#issuecomment-1400341051
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Razeeman** [comment]
Google spreadsheets also accepts this format. But I see your point. I'll switch this in the next update to minutes but still want to preserve seconds, maybe other users will find seconds useful, so it will be a number of minutes and seconds will be as a fraction of minutes, so "01:30:30" will be 90.5. Will this be ok?

**Comment by rudolfmu** [comment]
Simply make two fields in the .csv, total minutes (no rounding) and seconds. Then it is easy for everyone to pick their needs. It is much easier to add two fields than it is to pluck a string apart in a spreadsheet.
Most people will want to account for their work on different projects, they will only use name and minutes. Who wants seconds has them. A printout of the .csv with the minutes field would even be good enough for use with a pocket calculator.
Your other fields are fine for documentation.
And again, thanks for listening.


Am 24. Januar 2023 07:48:22 UTC schrieb Anton Razinkov ***@***.***>:
>Google spreadsheets also accepts this format. But I see your point. I'll switch this in the next update to minutes but still want to preserve seconds, maybe other users will find seconds useful, so it will be a number of minutes and seconds will be as a fraction of minutes, so "01:30:30" will be 90.5. Will this be ok?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Razeeman/Android-SimpleTimeTracker/issues/67#issuecomment-1401507279
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Razeeman** [comment]
Changed the duration format to minutes in the latest commits. Will be in the next update.
