### ISSUE TITLE
[Suggestion] Change activity on Lock Screen

### ISSUE THREAD

**Issue by frearlv** [Razeeman/Android-SimpleTimeTracker#7]
Hi. Thanks for your app.

I've been using https://www.gljakal.com/wayd/ at work for a long time. And I happy with it.

But I have 2 problems:
- I only use Windows at work. But I want track activities outside.
- I always forget annotate the activities.

So the suggestion is:
- To be able to change activities on the Lock Screen as in https://play.google.com/store/apps/details?id=com.md.selfm.timetracking&gl=ES or https://play.google.com/store/apps/details?id=com.godmodev.optime.
- A periodic reminder to revise the current activity, as WAYD or the other apps do.

Thanks again, regards.

Fernando.

**Comment by bahalbach** [comment]
Only Android versions lower than 5.0 support lock-screen widgets.

**Comment by bahalbach** [comment]
The Show inactivity reminder should take care of the other suggestion. But perhaps that notification could be responded to to start a new activity.

**Comment by Mehlsine** [comment]
This feature would be quite useful. 

I currently have 'Show untracked time in records' option enabled for continuous retroactive time tracking and 'Show inactivity reminder' option to remind me about untracked activity, then I open the app on Records tab (there's a shortcut you can find and drag on homescreen by pressing and holding the app icon) and manually choose what I spent this time on, and it functions pretty much like SaveMyTime or SelfM.

But I could use lockscreen widget to save me 2-3 taps, that's for sure =)

**Comment by Mehlsine** [comment]
Actually, it's not lock screen widget but the app launching itself when user unlocks its phone (as far as I know, apps need 'appear on top' permission to be enabled to perform this action)

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestions and sorry for the late reply. Finally find a way to change activities from the lock screen. In the latest update I've added ability to change activities from the timer notification. Periodic reminder to revise current activity is still on the roadmap, there is a separate issue for this #24.

**Comment by frearlv** [comment]
Hello Razeeman.
Thank you for the effort, I'll try it asap.
Cheers.
Fernando.
