### ISSUE TITLE
Allow import without clearing existing Records (aka Merge Import)

### ISSUE THREAD

**Issue by pragma-** [Razeeman/Android-SimpleTimeTracker#72]
Let's say I have this fantastic app installed on my phone and on my tablet. Say I use it most of the time while on my phone and that's where I want to keep the main database. Sometimes I use it on my tablet. I want to be able to save a backup file on my tablet and transfer this backup file over to my phone. Then on my phone, I want to "merge import" this backup file from my tablet without deleting any Records from the phone.

I hope I explained this clearly. I want to be able to use this app on my phone and on my tablet. I want the Records I save on my tablet to be importable into my phone without affecting the Records already existing on my phone.

**Comment by pragma-** [comment]
Alternatively or additionally, perhaps make it possible to host the database on a personal server and send/fetch across the network? Or some type of syncing?

Admittedly supporting remote hosting of the database or syncing is probably a big undertaking requiring quite a bit of refactoring. That's why I instead proposed the original "Merge Import" idea since it's simple enough to implement and I'm sure many, if not most, of us are perfectly willing to manually do backups and transfer them to import them again. Thoughts?

**Comment by pragma-** [comment]
I noticed some open issues involving using a cloud provider like Google Drive. I'd much, much prefer to instead manually transfer my backup files across devices and use the "Merge Import" feature to keep my daily activities timeline private.

**Comment by Razeeman** [comment]
Hello! Sorry for the late response. Finally got to implementing it. There will be an option to import data from the backup without clearing existing data, also there will be a selection of which data to import. Thank you for the feedback!

<img width="395" alt="image" src="https://github.com/user-attachments/assets/9e813d02-20e8-4280-b10c-04fac93612e0">
<img width="395" alt="image" src="https://github.com/user-attachments/assets/d14c4ce2-420d-404a-95f2-ae3b5f0013dd">
