### ISSUE TITLE
Allow optionally setting End Time when starting a new record

### ISSUE THREAD

**Issue by pragma-** [Razeeman/Android-SimpleTimeTracker#73]
I have a certain Activity that I like to track. Most of the time I'm not sure how long it'll take me to complete the activity. But sometimes I do know exactly how long it'll take. For these times, I'd like to be able to optionally input the task's duration so I don't have to remember to open the app and stop the timer. This would be so great!

**Comment by mertbakir** [comment]
If the end time is known then it means you don't need a counter. You can use the second tab and log a new record instead of starting an activity counter.

**Comment by pragma-** [comment]
> If the end time is known then it means you don't need a counter. You can use the second tab and log a new record instead of starting an activity counter.

Oh, nice. I didn't think of doing this. This solves this issue for me.

**Comment by pragma-** [comment]
Well, I kind of liked that the counter tab showed the activity-in-progress ... but I can live with this, I guess.
