### ISSUE TITLE
Bigger elapsed time on notification

### ISSUE THREAD

**Issue by MicaelJarniac** [Razeeman/Android-SimpleTimeTracker#74]
Currently, the elapsed time on the notification is not only tiny, but actually hidden by default, and only shown when the notification is dragged down to expand.

I believe it'd be better for the elapsed time to be bigger, and always visible, and perhaps the "started at" time to be smaller and hidden.

Here are some examples of both a Simple Time Tracker notification and a stopwatch notification:
![image](https://user-images.githubusercontent.com/19514231/215875877-156c6318-3249-4889-ba7a-59e4dc515eea.png)

![image](https://user-images.githubusercontent.com/19514231/215875932-f6abb44b-f3f8-48b8-b98a-b80a536fbc8d.png)

In my opinion, it'd be better if the Simple Time Tracker notification was more like the stopwatch one, with the elapsed time big and always visible, and the starting time small and hidden when not expanded.

Buttons to pause and stop time tracking could also be useful on the expanded notification, similar to the ones on the stopwatch.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Duration was moved into collapsed notification in the latest commits. Will be in the next update. Also added Stop button.
