### ISSUE TITLE
Help with automation

### ISSUE THREAD

**Issue by yato5007** [Razeeman/Android-SimpleTimeTracker#77]
Before anything I really want to thank you for that great tool that measures our life..

I'm a mechanical engineer. So I don't know a lot about programming. But I really need to use that features comes with the automation
I spent more than 10 hours trying to understand and make it work but still I didn't achieve what I wanted..

So can you help with that please ?
![Screenshot_2023-02-07-08-27-41-637_com llamalab automate](https://user-images.githubusercontent.com/45288714/217156310-112274d7-8524-4587-8c4f-0809f83ad7ab.jpg)
I'm using "Automate" app with that..

what should I fill in activity class, Action , extras.
Also you said in the app I must use "extra_activity_name" after that put the activity name.. can you give me an example for that.
Actually I have a lot of questions but I'm sure if you helped me with that I can lead the way by myself..

Thanks

**Comment by yato5007** [comment]
Guys finally that's works..
The problem was from Automate App
You can use MacroDriod app is very easy and powerful..
![Screenshot_2023-02-07-09-14-50-704_com arlosoft macrodroid](https://user-images.githubusercontent.com/45288714/217163591-70d77ce2-9fe1-46d6-96f3-c14882314d29.jpg)
Choose that to use the parameters in the app..



![Screenshot_2023-02-07-09-14-06-536_com arlosoft macrodroid](https://user-images.githubusercontent.com/45288714/217163720-e5a81192-8f87-4b69-a8ec-5ee3a07b843b.jpg)
This is an example 👍🏼🤍

Thanks

**Comment by Razeeman** [comment]
Hello. Glad it worked out! I didn't research Automate app but saw that it has "send broadcast" or "receive broadcast" triggers. It is possible that it would also works if using them.

**Comment by lgwapnitsky** [comment]
Just found this app, and like it but I must be dense on getting the intent to work in Tasker.  How do I define the activity to start?

![Image](https://github.com/user-attachments/assets/21286d28-4035-4d4a-9ede-833e115c7998)

**Comment by Razeeman** [comment]
Hello! Extras are defined as pairs of key and value. "Extra_activity_name" is the key, and it's value should be the name of the starting activity. Hope this helps!

**Comment by lgwapnitsky** [comment]
Perfect, thanks!
