### ISSUE TITLE
Reduce minimum widget size

### ISSUE THREAD

**Issue by 1over137** [Razeeman/Android-SimpleTimeTracker#78]
My device can comfortably fit 8 rows of icons, but the single activity widgets forces me to have at most 6 rows, otherwise it needs two rows for some reason, which is a huge waste of space on my screen. Please set the minimum widget size to a lower value.

**Comment by Razeeman** [comment]
Can you please specify your phone's model and os version? Some screenshots would be useful as well if it is possible.

**Comment by 1over137** [comment]
![image](https://user-images.githubusercontent.com/22680475/221105780-4f426867-15bc-4384-8467-5fe00dac88b9.png)
Phone is a Pixel 7, 2400x1080, Android 13, using Lawnchair (basically the same as the stock launcher).
The shown screenshot is at 6 rows, which is the most rows I can have until simple time tracker wants to use two rows for each icon. However as you can see there is still a lot of space between rows. It may not look good to everyone, but I would appreciate being able to use more rows.

**Comment by 1over137** [comment]
Since these widgets are meant to be 1x1 without any sub-components for touch, the minimum specified size can be as small as possible to give the user maximum control. If a user can accept app icons being at a certain size, then he should also be able to use these widgets at the same size.

**Comment by Razeeman** [comment]
Thank you for the explanation. Was able to reproduce this on emulator using Lawnchair. Reduced widgets default size in the latest commits, will be in the next release.

By the way, Nova launcher seems to work fine on current app version and with even greater grid row count.
