### ISSUE TITLE
［feature］Tweet it when star/end events

### ISSUE THREAD

**Issue by liuqin19980818** [Razeeman/Android-SimpleTimeTracker#79]
It`s cool when you tweet your events on twitter

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. I think this can be possible with the use of third-party automation apps. In the latest update was added "Send events" setting, which can be enabled to send events to these apps when activities in Simple Time Tracker are started or stopped. And apps like Macrodroid can react to these events by posting a tweet.
