### ISSUE TITLE
[Automation] Stop Activities Intents

### ISSUE THREAD

**Issue by Verlichev** [Razeeman/Android-SimpleTimeTracker#80]
Firstly, I would like to thank you for this great app, the more I play with it, the more I like it. When I figured out, it has easy automation integration, it helped a lot in my projects. I use it with MacroDroid.

The features I would like to recommend.
Send Intent -> Stop all active activities
Send Intent -> Stop last activated activity
Send Intent -> Stop longest running activity

I don't know if this features already exist, but they would be of great use to me. If they do, I appologize and may I get the right commands to use them with?
If they do not, I would like to request them, if it is not too much hasle.

Kind Regards

**Comment by Razeeman** [comment]
Hello! Thank you for the suggest. I think it would be easy to implement. One thing is, what does "stop last activated activity" would mean? Would that mean the shortest activity, one which "time started" was the latest?

**Comment by Verlichev** [comment]
Wow, that was a fast response!!!
Yes, that is what I meant. Apologies for unclear request. Basicly, I would like to automate stoping an activity, when a new one starts automatically.

Thank you!

**Comment by Razeeman** [comment]
Thank you for the explanation. By the way, there is a setting "allow multitasking", if it is disabled it does exactly this, stop current activity when new one starts.

**Comment by Verlichev** [comment]
Oh, sorry I missed that. Didn't even think about that possibility. Thank you. That will solve some of my current obstacles.
Otherwise, thank you for fast responses, and if you are willing to implement my suggestion in the future, it will be greatly appreciated!

**Comment by Fafo2710** [comment]
@Verlichev hello! i use macrodroid too! could you help me how did you create the macro to start and stop an activity? wich action did you use?

**Comment by Razeeman** [comment]
@Fafo2710 Hello. You can check this thread #77, maybe it will help.

**Comment by alkero** [comment]
Intents implementation is really a great addition, I use it with Tasker and it opens a lot of possibilities.

Personally I would like to have a "stop current activity and restart previous activity". 
For example to be able to start a "social media" activity when I open Facebook, Instagram, etc., and then to automatically come back to my previous activity once I close the application.

**Comment by Razeeman** [comment]
Added new intents for stopping activities. Will be in the next update.

Also added new intent to restart previous activity. It doesn't stop current activity, I think that can be done by disabling multitasking setting.
