### ISSUE TITLE
Separate View for Goals

### ISSUE THREAD

**Issue by mertbakir** [Razeeman/Android-SimpleTimeTracker#82]
Goals have great potential, but they are not featured well in the app, imho. I think another tab would be useful just to track daily and weekly goals on activities.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. At the moment goals are shown on the statistics tabs. Can you explain a little why a separate tab would be more convenient? My main concern is that for people who don't use goals this separate tab will be always empty, seems like a waste.

**Comment by mertbakir** [comment]
Yes, I realised goals are listed in the 3rd tab. Yet, they are listed below and are not seen at the first look. I think highlighting goals can be beneficial for users and users who is not using goals may start using this feature in this case.

**Comment by ghost** [comment]
I do not use this functionality and would not like to see a separate tab for Goals (*Simple* Time Tracker, yes?). But moving the goals block to the top of the statistics tab seems like a good idea.
I think this will be useful for maniacs who track as much of their time as possible. In this case, they will be able to immediately see the important activities without digging into the monstrous number of others.

**Comment by Razeeman** [comment]
Added a setting to show goals on a separate tab. It is in the latest release.
