### ISSUE TITLE
FR: Regarding the transfer of different data between entities.

### ISSUE THREAD

**Issue by YIRU69** [Razeeman/Android-SimpleTimeTracker#87]
Hello, I have been using your tool for a long time and I am really happy to have such a passionate developer like you. I have a suggestion for you, which is also a problem that I really want to solve. I have a requirement and I am currently unclear about how to achieve it. If possible, please let me know.

Assuming I have two categories, A and B, and now I want to delete all data in B and replace it with A. In other words, I want to migrate the data from B to A. Is it possible to achieve this?

**Comment by Razeeman** [comment]
Hello!

At the moment this is only possible by editing a backup file which would require some tinkering. Backup file at the moment is just a text file that can be edited.

But this would be a useful feature, so I'm planning to add some actions for mass data editing. One option would be this merge or data transfer between activities. Another suggested option is to change record tag into its own activity.

Can't tell for sure when it will be implemented though.

**Comment by YIRU69** [comment]
Good news! I can wait for it!

**Comment by Razeeman** [comment]
Added "Data edit" screen in the latest commits. Will be in the next update.
