### ISSUE TITLE
Display activity entry duration distribution

### ISSUE THREAD

**Issue by tomzx** [Razeeman/Android-SimpleTimeTracker#9]
When you click on an entry in the 3rd tab (the statistics page), in the entry page it would be great if we could see an histogram/bar chart of the number of entry for a given bucket duration (e.g., 0-5 minutes, 5-10, ...). This would allow us to see what the distribution of duration look like for this given entry.

This additional chart could go just above the shortest/average/longest block of information since it's related to it.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion, I finally got to it. Implemented in the latests commits and will be in the next update.
