### ISSUE TITLE
[Feature request]: Calendar view weekly

### ISSUE THREAD

**Issue by UttermostUsername** [Razeeman/Android-SimpleTimeTracker#90]
The calendar view appears to only be able to show a single day at a time.
It would be nice to select a range of days to view simultaneously in calendar view like in the following image.

![image](https://user-images.githubusercontent.com/91044478/225166937-f90a60bd-0638-426d-bec0-6f09cc305ce0.png)

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Found a way to do it with minimal pain. Implemented in latest commits, will be in the next update. Will look something like this:

![Screenshot_1683977469](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/5223302/479f95d8-37b7-4497-85d0-2d588f2aa405)
![Screenshot_1683977494](https://github.com/Razeeman/Android-SimpleTimeTracker/assets/5223302/75239f05-66c7-4cd8-b4ab-ac541a016b26)

**Comment by UttermostUsername** [comment]
Look forward to the release. Thanks!
