### ISSUE TITLE
FR: Minus time 

### ISSUE THREAD

**Issue by EldarAron** [Razeeman/Android-SimpleTimeTracker#91]
I use Simple Time Tracker to track my days at work. At my workplace we have flexible working days. That means that I one day can work 9 hours and another 7 hours.

But I have to distinguish between extra time worked over 7,5 hours and minus time in the company HR system. I can accumulate plus time in my time bank.I had to manually calculate ho much time I have in my time bank in the app. I started tagging plus time as an own tag; timebank, but I'm not able to set minus time in the app. Again I have to calculate manually.

Therefore it would be nice to be able to set the start time to say 16:00 and endtime to 15:00. Becuase I left for 1 hour early one day. That way get -1 hour registered on the tag; timebank. The total for week/month/year/overall statistic would be correct and easy to comepare with the HR system. To make sure people don't make a mistake. A setting in the tag could be added to allow minus time on that specific tag or mor generally in the settings page.

I would really appreciate if this feature could be added. 😊

**Comment by Razeeman** [comment]
Hello! Can you check this thread #86? Maybe it will help.

**Comment by Razeeman** [comment]
Closing issue for now, please reopen if I can help with anything else.
