### ISSUE TITLE
[Suggestion] Remove activity tab hints

### ISSUE THREAD

**Issue by ghost** [Razeeman/Android-SimpleTimeTracker#95]
Hello. Thank you for your work.

I suggest removing the hints "Click... to", "Long click... to" from the activity screen or creating an option for this in the settings. Hints take up a lot of space, while almost immediately losing relevance.

**Comment by Razeeman** [comment]
Hello! Sorry for the late reply and thank you for the feedback. Not sure hints take up a lot of space, so probably will stay as it is for now.
