### ISSUE TITLE
[Feature request] Customizable order of activities in the first tab

### ISSUE THREAD

**Issue by froyglez** [Razeeman/Android-SimpleTimeTracker#96]
I have a daily routine with a specific order of activities that doesn't follow alphabetical order, so it would be great to be able to say, press, hold and reorder the activities in the first tab to have a custom order in it. And of course leave the current order rules as a default option.

**Comment by ghost** [comment]
If I understand you correctly, this feature is already implemented.
Go to 4th tab -> Display Settings -> Sort activity -> Manually

**Comment by froyglez** [comment]
Yes! Thank you so much
