### ISSUE TITLE
[Feature request]: add times a day/week/month/etc option

### ISSUE THREAD

**Issue by froyglez** [Razeeman/Android-SimpleTimeTracker#99]
When creating a new activity, one can set a goal time. It would be great if it is added to the app another option which allows users to set a goal number of times of the activity a day, or a week, or a month, etc. Something like a habit tracker. Unless the goal number is reached, the activity icon in the first tab remains with a distinctive sign (for example, a red outline). This feature allows not only to track the time spent in activities, but also it allows to easily visualize if one is completing his or her habits. It could also be added another graphic that shows this feature statistics.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Added goal count in the latest release. Still on the fence about adding goals to the activity cards on the main tab.

**Comment by Razeeman** [comment]
Also added a checkmark on activities on the first tab.
